### ISSUE TITLE
Commutativity of multiplication not honored by `compareTo`

### ISSUE THREAD

**Issue by raner** [axkr/symja_android_library#1030]
**Describe the bug**

I didn't see an option for just posting a question issue, so this issue may not necessarily be a bug, just some misunderstanding on my part.
In a nutshell, it appears that the commutativity of multiplication is not honored by the `compareTo` method, and that multiplication expressions are not considered equal if the order of the operands differs.

**To Reproduce**

```
  @Test
  public void testComplexMultiplicationEquality()
  {
    IExpr i = S.I;
    IExpr two = IntegerSym.valueOf(2);
    IExpr left = i.multiply(two);
    IExpr right = two.multiply(i);
    assertEquals(left + "/" + right, 0, left.compareTo(right));
  }
```
Error result:
```
java.lang.AssertionError: 2*I/I*2 expected:<0> but was:<1>
	at tests.SymjaExercises.testComplexMultiplicationEquality(SymjaExercises.java:34)
```

**Expected behavior**

My expectation is that `2⋅i` would be considered equal to `i⋅2`.

**Java**
 - GraalVM 22.1.0, Java 17.0.3
 - MacOS 14.0

**Comment by axkr** [comment]
> **Describe the bug**
> 
> I didn't see an option for just posting a question issue, so this issue may not necessarily be a bug, just some misunderstanding on my part. In a nutshell, 

There's a "discussion page":
- https://github.com/axkr/symja_android_library/discussions

>it appears that the commutativity of multiplication is not honored by the `compareTo` method, and that multiplication expressions are not considered equal if the order of the operands differs.
> 
> **To Reproduce**
> 
> Steps to reproduce the behavior:
> 
> ```
>   @Test
>   public void testComplexMultiplicationEquality()
>   {
>     IExpr i = S.I;
>     IExpr two = IntegerSym.valueOf(2);
>     IExpr left = i.multiply(two);
>     IExpr right = two.multiply(i);
>     assertEquals(left + "/" + right, 0, left.compareTo(right));
>   }
> ```
> 
> Error result:
> 
> ```
> java.lang.AssertionError: 2*I/I*2 expected:<0> but was:<1>
> 	at tests.SymjaExercises.testComplexMultiplicationEquality(SymjaExercises.java:34)
 
`S.I` is the pure symbol, which must be converted to `F.CI` either by the parser or by the `EvalEngine#evaluate()` method:

```java
 @Test
  public void testComplexMultiplicationEqualityIssue1030a() {
    // I - Imaginary unit - internally converted to the complex number `0+1*i` by the evaluation
    // engine. 
    IExpr i = S.I;
    IInteger two = F.ZZ(2);
    EvalEngine engine = EvalEngine.get();
    IExpr left = engine.evaluate(i.multiply(two));
    IExpr right = engine.evaluate(two.multiply(i));
    assertEquals(left + "/" + right, 0, left.compareTo(right));
  }
```

If you use the `IComplex` number `F.CI` directly you don't need the evaluation step:

```java
  @Test
  public void testComplexMultiplicationEqualityIssue1030b() {
    // Complex imaginary unit "0 + I". The parsed symbol "I" is converted on input by the parser to
    // this constant.
    IComplex i = F.CI;
    IInteger two = F.ZZ(2);
    IExpr left = i.multiply(two);
    IExpr right = two.multiply(i);
    assertEquals(left + "/" + right, 0, left.compareTo(right));
  }
```

**Comment by raner** [comment]
Thanks for the prompt response, that answers my question. I'll be sure to use the discussion page next time!
