### ISSUE TITLE
Need add new method that can translate Latex-syntax to Math text.

### ISSUE THREAD

**Issue by wzw617248224** [axkr/symja_android_library#105]
There is a Latex-synax:  
`\operatorname { sin } 30 ^ { \circ }`
in image it shows like this [PastedGraphic-1.png](https://www.google.com/imgres?imgurl=https%3A%2F%2Fi.ytimg.com%2Fvi%2FjdoO2B80bCc%2Fmaxresdefault.jpg&imgrefurl=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DjdoO2B80bCc&docid=zblyvcVYHYxm0M&tbnid=LqXfsnFNKK6p9M%3A&vet=10ahUKEwjvr8Skt7DfAhVIXrwKHQX1BCUQMwhHKAkwCQ..i&w=1280&h=720&safe=active&bih=917&biw=1635&q=sin30&ved=0ahUKEwjvr8Skt7DfAhVIXrwKHQX1BCUQMwhHKAkwCQ&iact=mrc&uact=8). 
The question is if I want to calculate it, I must translate this into that sin(30*degree).

I found a lot of libs, it does support Latex to math text. I’m here want a help, is there have some method can translate a Latex to math text(best in Java)? Thank you very much.

 The most important Latex- expressions:
`\operatorname { sin } \frac { \pi } { 2 }`
`1 + 2 - 3 \times 4 \div 5`
`\operatorname { sin } \frac { \pi } { 2 }`
`x ^ { 2 } + 1 = 2`
`\left ( 1+2 \right )^{2}`

**Comment by axkr** [comment]
Started a new branch:
* https://github.com/axkr/symja_android_library/tree/issue105

A first prototype:
* no error handling  
* only some binary operators, no pre- or postfix operators at the moment
* note: TeX syntax may be ambigious and therefore you can get unexpected results

Some JUnit test cases:
* https://github.com/axkr/symja_android_library/blob/issue105/symja_android_library/matheclipse-core/src/test/java/org/matheclipse/core/form/tex/TeXConverterTestCase.java

**Comment by wzw617248224** [comment]
hi, thanks for you contribution. For now, I want to include this branch into my android project. How should I do?

**Comment by axkr** [comment]
@tranleduy2000 can you please add these changes to the android Java 7 fork:
https://github.com/tranleduy2000/symja_android_library

**Comment by tranleduy2000** [comment]
@axkr this project is overhead when run on Android devices. The purpose of LaTeX is use for displaying, rarely use for calculating,  so we don't need to port to Java 7.
@wzw617248224 You can clone this project and import to your Android project. Then set language level to Java 8 and Android API 24 

```Gradle
android {
    defaultConfig {
        targetSdkVersion 24
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
```
