### ISSUE TITLE
Incorrect result when calculate Int(1/Sqrt(9*x^4+1),{x,0,999})

### ISSUE THREAD

**Issue by tranleduy2000** [axkr/symja_android_library#109]
![image](https://user-images.githubusercontent.com/19369448/51075258-d2a16a00-16bb-11e9-9803-52046d678359.png)
![image](https://user-images.githubusercontent.com/19369448/51075263-d6cd8780-16bb-11e9-9cf2-58c16d3ea92f.png)

**Comment by axkr** [comment]
The last commit should solve this issue.

For a better numerically evaluation it may be worth to use 
[jtem/ellipticFunctions](https://gitlab.discretization.de/jtem/ellipticfunctions/tree/master/src/de/jtem/ellipticFunctions)
which seem to be implemented on the `Complex` domain.

Any help is appreciated.

**Comment by axkr** [comment]
Created #131  for this now.
