### ISSUE TITLE
Matrix power give wrong result

### ISSUE THREAD

**Issue by tranleduy2000** [axkr/symja_android_library#11]
# Submit a feature request or bug report

Replace any "X" with your information.

---

### Is this a request for a feature or a bug report?

Yes, this is bug

### What is the current behavior?

X

### If this is a bug report, please provide steps to reproduce:

X

![image](https://user-images.githubusercontent.com/19369448/34460906-14796ff4-ee4f-11e7-942f-ba5c51a26c4a.png)

![image](https://user-images.githubusercontent.com/19369448/34460897-af0e8bb8-ee4e-11e7-8836-d7d1d6c8d591.png)

### What is the expected or desired behavior?  

Fix it as soon as possible

### Please provide use cases for changing the current behavior:

X

### Please describe your development environment (OS, browser, etc.):

X

### Other relevant information:

X

**Comment by axkr** [comment]
Symja works more like Mathematica and don't use the matrix power rules for the ^operator.

If you do a:
`
Attributes(Power)
`
you see that Power has the Listable attribute.

So
`
{{2,1},{1,1}}^(-2)
`

is computed as:
`
{{2^2,1^2},{1^2,1^2}}
`
