### ISSUE TITLE
Systems with decimal numbers and power of 2 cannot be solved

### ISSUE THREAD

**Issue by predictron-cloud** [axkr/symja_android_library#117]
First of all thanks for very fruitful lib! As far as I googled, it is the only one comprehensive and maintainable Java symbolic algebra library. I plan to use it in my java ML application.

I need to solve system of nonlinear equations. In simple case all is ok, e.g. this works:
`Solve({x+y==9, y==2*x+2}, {x,y})`
`Solve({x+y==9.1, y==2*x+2}, {x,y})`
`Solve({x+y^2==9, y==2*x+2}, {x,y})`
However this doesn't work:
`Solve({x+y^2==9.1, y==2*x+2}, {x,y})`
Is it the desired behavior, or there is some trick to make it work?
(of course, I can replace everything with fractional, like 9.1 == 9/10 and it will work, but it looks weird)

In addition to that in my case system of equations can contain sin, log, exp. Namely, I need to obtain numeric decimal values of variables. Wolfram alpha and Maple can solve such kind of systems. Are there any plans to support this kind of systems in future?

**Comment by axkr** [comment]
@predictron-cloud  in your example the expression `_` represents a "pattern expression".
Do you mean something like this?

```
  Solve({x+y^2==9/10, y==2*x+2}, {x,y})
```

For numericalsolutions you can use [FindRoot](https://github.com/axkr/symja_android_library/blob/master/symja_android_library/doc/functions/FindRoot.md)

**Comment by predictron-cloud** [comment]
@axkr, by "_" I tried to make italic font, in github =). I edited the original message. Yes I meant something like your example, but I wonder, if it works with 91/10 in the right-hand side, why it doesn't work with 9.1 there?

**Comment by axkr** [comment]
With [commit 6ed480c](https://github.com/axkr/symja_android_library/commit/6ed480c4611196ec1b4850db25d0fa8d2a12e0e4) it should also word with numeric expressions.

**Comment by predictron-cloud** [comment]
Great news, thanks a lot. However, what about more complex cases with sin and exp (which can be solved, of course). Are there any plans to support systems of equations with them?

As for FindRoot, I cannot see in docs how to use it with systems of equations.

**Comment by axkr** [comment]
Simple cases for Sin , Cos should already be solvable. Do you have examples?

**Comment by predictron-cloud** [comment]
For example, I want to find roots of: Solve({sin(x)-11==y, x+y==-9}, {x,y})
It returns the same string (as I understand it is sign, that it cannot be solved), however Alpha can find roots of it:
https://www.wolframalpha.com/input/?i=solve+sin(x)-11%3D%3Dy,+x%2By%3D%3D-9

BTW: Ctrl+C (copy keyboard shortcut) doesn't work in web interface (http://matheclipse.org/).

**Comment by axkr** [comment]
OK in the end your example can be converted in an expression with 1 variable which can be solved with FindRoot. 
Have to think about how to automize this?

**Comment by predictron-cloud** [comment]
Yes, in my application I have arbitrary number of equations (2<N<8), which can have arbitrary type of operators (sin, exp). This equations are obtained automatically by Genetic Programming and I need to solve them to get numeric value of one of the variables.

**Comment by predictron-cloud** [comment]
Thanks, the initial problem: Solve({x+y^2==9.1, y==2*x+2}, {x,y}) -  is fixed!
And this works as well: Solve({2==x-0.091*y, y==0.054-0.0171*z^2,x==z+z^2+1}, {x,z,y})
Unfortunately, sin() and exp() still cannot be used in equations systems. Could them be implemented in the future?

**Comment by axkr** [comment]
Pleased add some examples. Note I haven't updated the web demo at the Moment.

**Comment by predictron-cloud** [comment]
Yes, I noted that. For example, this: util.eval("Solve({2==x-0.091*y, y==0.054-0.0171*z, x==exp(z)+1}, {x,z,y})").toScript() cannot be calculated, but it has solution: https://www.wolframalpha.com/input/?i=solve+2%3Dx-0.091*y,+y%3D0.054-0.0171*z,+x%3Dexp(z)%2B1 

P.S. I need just numerical solution. so NSolve should be enough, but it doesn't solve such kind of problems.

**Comment by predictron-cloud** [comment]
Also: is there convenient way to get values from AST to java Map? For example, if AST looks like: {{energy->-0.48821457524827644,speed->2.0219887986501504,temperature->0.2587207439017716},
 {energy->22.16775016762962,speed->47.33391828440595,temperature->533.3999937482979}}

**Comment by axkr** [comment]
A "rules to map" method could be implemented like the method below.
But what do you expect for the "list of list of rules" case?
An ArrayList of maps?

```
	public static Map<IExpr, IExpr> rules2Map(IAST astRules) {
		final Map<IExpr, IExpr> map = new HashMap<IExpr, IExpr>();
		IAST rule;
		if (astRules.isList()) {
			// {{a->b,...},{...}....}
			// what to do in this case?
		} else if (astRules.isList()) {
			// {a->b, c->d, ...}
			if (astRules.size() > 1) {
				// assuming multiple rules in a list
				for (final IExpr expr : astRules) {
					if (expr.isRuleAST()) {
						rule = (IAST) expr;
						map.put(rule.arg1(), rule.arg2());
					}
				}
			}
		} else if (astRules.isRuleAST()) {
			// a->b
			rule = astRules;
			map.put(rule.arg1(), rule.arg2());
		}
		return map;
	}
```

**Comment by axkr** [comment]
@predictron-cloud: I will close this. If it's still open please create a new issue and reference this issue.
