### ISSUE TITLE
Operations for Gaussian integers

### ISSUE THREAD

**Issue by axkr** [axkr/symja_android_library#119]
The [`ComplexSym` implementation](https://github.com/axkr/symja_android_library/blob/master/symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/ComplexSym.java) is missing some operations for [Gaussian integers](https://en.wikipedia.org/wiki/Gaussian_integer):

- implement euclidian division, gcd,...

**Comment by gibeoom** [comment]
Hi, @axkr can I take this up?

**Comment by axkr** [comment]
@gibeoom Yes of course I assigned your account.

**Comment by axkr** [comment]
`PrimeQ `and `FactorInteger `already have a `GaussianIntegers->True` option.

See:
- https://github.com/axkr/symja_android_library/blob/master/symja_android_library/doc/functions/PrimeQ.md
- https://github.com/axkr/symja_android_library/blob/master/symja_android_library/doc/functions/FactorInteger.md
- https://github.com/axkr/symja_android_library/blob/master/symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/numbertheory/GaussianInteger.java
-

**Comment by gggch414** [comment]
Hi @axkr, I'm  @gibeoom  's friend. He said he wanna solve this asap but he need someone help. So I think I can do this too. Can you assign it to me?

**Comment by axkr** [comment]
@gggch414 thanks for your help. I assigned your account.

**Comment by OleksandrMariupol** [comment]
Hi, Is this issue still open? I want to try to solve it

**Comment by axkr** [comment]
@OleksandrMariupol I assigned your account.

@gggch414 can I remove your account from this issue?

**Comment by OleksandrMariupol** [comment]
No, do not remove my account from this issue,  @axkr Please can you assign me again  for this issue, I accidentally pressed unassign

**Comment by axkr** [comment]
done.

**Comment by OleksandrMariupol** [comment]
Hi. I looked at the question briefly. I would like to clarify few items. What do you mean by "implement euclidian division"? Based on my knowledge of Math. There is no "euclidian division", there is an Euclidean algorithm for finding GCD, maybe you meant the division of Gaussian numbers with the remainder? When we divide two Gaussian numbers, they can be completely divided. Or if we want to get a Gaussian number again need to  find the remainder. Or it may turn out to be a complex number with fractionals if we want to get out of f Gaussian rings. It's about division.
I have to write methods for class ComplexSym? How will the method accept Gaussian integers? How we’ll return the Gaussian integers?In ComplexSym there is no type Gaussian integers. Thanks in advance.

**Comment by axkr** [comment]
With "euclidian division" I refer to the Wikipedia entry. Did you read that article?
- https://en.wikipedia.org/wiki/Gaussian_integer#Euclidean_division

**Comment by OleksandrMariupol** [comment]
Yes, I have read, this is wikipedia, what about Math books?). They say about "Euclid's division algorithm" . And I ask these questions to clarify the purpose of the task, different sources may give different information or I can miss something.  You need division with the remainder,  and GCD? And what about questions "I have to write methods for class ComplexSym? How will the method accept Gaussian integers? How we’ll return the Gaussian integers?" I want to clarify the requirements and job details.

**Comment by OleksandrMariupol** [comment]
http://www.cs.cornell.edu/courses/cs2800/2017sp/lectures/lec29-division.html

**Comment by OleksandrMariupol** [comment]
Hi axkr. I have created this pull request https://github.com/axkr/symja_android_library/pull/178/files 
Can you please take a look? Any comments are welcome. This is the method to find an integer part of division for Gaussian integers. I can write a method for fraction part. But how we can return in one method values for both, is this important to return both in one method or we can have two methods?
Thanks in advance.

**Comment by axkr** [comment]
See comments in the PR

**Comment by axkr** [comment]
Can you please improve your implementation for these special cases:
https://github.com/axkr/symja_android_library/blob/9703d086188f9132c6dddae0d63fb92fe49814d1/symja_android_library/matheclipse-core/src/test/java/org/matheclipse/core/expression/ComplexSymTest.java#L405

**Comment by OleksandrMariupol** [comment]
Hi axkr. Thank you very much for your quick reply. I think that it already works. It’s great with these specific cases, as by definition. 
 Properties of GCD. If a GCD is known, then any of the three numbers associated with it will also be a GCD. In particular, if one of the GCD is a divisor of one, then the other three GCD will be also the divisorіs of one.
    Gaussian numbers are mutually prime if and only if their GCD is a divisor of one. 
That is why, if 1 is the largest divisor, then -1, i, -i will also be the correct answers. My function is looking for one of the four options, using the Euclidean algorithm, ie -1 is the correct answer. 1 is not always expected in those cases which you listed. What do you think about this?

Regards,

**Comment by axkr** [comment]
Yes, but for comparison it's better to "normalize" the result.

See example here: 
- https://www.wolframalpha.com/input/?i=GCD%5BI%2C-I%5D

**Comment by OleksandrMariupol** [comment]
OK,  if -15-7i and -10+11i, GCD my method return -i. Should my method return 1, too?
Regards,

**Comment by axkr** [comment]
@OleksandrMariupol yes

**Comment by OleksandrMariupol** [comment]
Hi again, axkr. I see you merged pull request, thank you. However, I added code for these special cases, here is the commit https://github.com/OleksandrMariupol/gaussian_integer/commit/5485e24e9d62487ee719696b955813032bbe9535
Would you like to include them? Let me know if I should create new pull request.

**Comment by axkr** [comment]
Yes please create a new PR.

**Comment by OleksandrMariupol** [comment]
I created new pull request https://github.com/axkr/symja_android_library/pull/180

**Comment by OleksandrMariupol** [comment]
I have created new PR https://github.com/axkr/symja_android_library/pull/181/files

**Comment by axkr** [comment]
@OleksandrMariupol did some clean up in f7da166.

If you like you can refactor the `ComplexSym#gcd()` and `ComplexSym#integerAndRemainderDivisionGuassian()` methods by making them static and moving them to:
- https://github.com/axkr/symja_android_library/blob/master/symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/numbertheory/GaussianInteger.java

See:
- https://stackoverflow.com/questions/32823675/method-refactoring-in-eclipse

Otherwise I would like to close this issue and open a new issue for further operations.

**Comment by axkr** [comment]
You can now test in the online demo:
- http://matheclipse.org/input?i=GCD%285%2B3%2AI%2C%202-8%2AI%29

**Comment by OleksandrMariupol** [comment]
Hi axkr. Are there any more pressing issues I can help with? 
Regards,

**Comment by axkr** [comment]
Can we discuss here: https://gitter.im/symja_android_library/Lobby

**Comment by OleksandrMariupol** [comment]
Ok, I think we can.
