### ISSUE TITLE
How to calculate cross product of two vectors?

### ISSUE THREAD

**Issue by tranleduy2000** [axkr/symja_android_library#12]
![image](https://user-images.githubusercontent.com/19369448/34533283-27833536-f0ec-11e7-93e2-950165063732.png)
![image](https://user-images.githubusercontent.com/19369448/34533289-2f22eea8-f0ec-11e7-953c-dc388f7178ee.png)

**Comment by axkr** [comment]
Please try these examples:
```
>> Cross({x1, y1, z1}, {x2, y2, z2})
{-y2*z1+y1*z2,x2*z1-x1*z2,-x2*y1+x1*y2}
 
>> Cross({x, y})
{-y,x}
```

**Comment by axkr** [comment]
`Cross({a,b}, {c,d})` now gives `-b*c+a*d`

**Comment by tranleduy2000** [comment]
Thanks
