### ISSUE TITLE
[BUG] UnsupportedOperationException occurs when calculating integral of Ln(x)^2

### ISSUE THREAD

**Issue by tranleduy2000** [axkr/symja_android_library#120]
When I calculate symbolic integral, it give correct result. 

![image](https://user-images.githubusercontent.com/19369448/54818103-153e7e80-4ccb-11e9-9488-d0fe16e3f227.png)

But numeric integral give error:

![image](https://user-images.githubusercontent.com/19369448/54817591-e96ec900-4cc9-11e9-97a8-05478e11e51b.png)

![image](https://user-images.githubusercontent.com/19369448/54817580-e378e800-4cc9-11e9-84a5-14181ef5fabe.png)

**Comment by axkr** [comment]
Probably Log(0) causes the problem. Will take a look at the weekend.

**Comment by axkr** [comment]
Fixed in latest demo http://matheclipse.org/
