### ISSUE TITLE
Exception occurs when calculate determinant of non-square matrix

### ISSUE THREAD

**Issue by tranleduy2000** [axkr/symja_android_library#121]
System crashed after calculate these expression below, I think it should be return unevaluated expression.

```
Det({{1, 1, 1}, {2, 2, 2}})
```

![image](https://user-images.githubusercontent.com/19369448/55300297-01301500-5461-11e9-9168-fdc04382b988.png)

**Comment by tranleduy2000** [comment]
```
MatrixPower({{2},{1}},2)
```
![image](https://user-images.githubusercontent.com/19369448/55300513-02157680-5462-11e9-93c7-6b27c545dd64.png)

**Comment by tranleduy2000** [comment]
```
Dot({{0,2},{-8,2}},{{{0},0},{0,3}})
```
![image](https://user-images.githubusercontent.com/19369448/55300672-c202c380-5462-11e9-8e36-60b0d124f6b8.png)

**Comment by tranleduy2000** [comment]
Another similar issue:
```
factor(x^(12)-y^(12),GaussianIntegers->True)
```
![image](https://user-images.githubusercontent.com/19369448/55415090-a1d42100-5596-11e9-81b1-61c7006ec957.png)

**Comment by axkr** [comment]
Fixed in latest demo http://matheclipse.org/
