### ISSUE TITLE
Calculating polynomial discriminant of quintic gives wrong result

### ISSUE THREAD

**Issue by tranleduy2000** [axkr/symja_android_library#122]
```
discriminant((2*x^5)-(19*x^4)+(58*x^3)-(67*x^2)+(56*x)-48,x)
```
![image](https://user-images.githubusercontent.com/19369448/55414324-160dc500-5595-11e9-91cb-824eca0907d1.png)

![image](https://user-images.githubusercontent.com/19369448/55414363-2625a480-5595-11e9-8f75-3eafd0aee196.png)

**Comment by axkr** [comment]
See: https://github.com/kredel/java-algebra-system/issues/10

**Comment by axkr** [comment]
Fixed in latest demo http://matheclipse.org/
