### ISSUE TITLE
Calculating 1/(2+Sqrt(5)) + 1/(2-Sqrt(5)) should return -4

### ISSUE THREAD

**Issue by tranleduy2000** [axkr/symja_android_library#125]
```
1/(2+Sqrt(5)) + 1/(2-Sqrt(5))
```
![image](https://user-images.githubusercontent.com/19369448/55780969-56100300-5ad3-11e9-87a4-613583a2b27f.png)

![image](https://user-images.githubusercontent.com/19369448/55780976-5a3c2080-5ad3-11e9-8e5a-ecdc06a2c971.png)

**Comment by axkr** [comment]
Did you try with Simplify() function?

**Comment by tranleduy2000** [comment]
Thanks for your suggestion.

**Comment by axkr** [comment]
Please keep in mind that Simplify() can reduce the performance for larger expressions.
