### ISSUE TITLE
Can't evaluate anything

### ISSUE THREAD

**Issue by wblachowski** [axkr/symja_android_library#129]
Hello guys, I have some problems with basic evaluation. Instead of calculating the result, `ExprEvaluator.eval()` function returns the input string (sometimes slightly modified), e.g:

`new ExprEvaluator().eval("1+1").toString() //returns 1+1`
`new ExprEvaluator().eval("Solve(x==17-3,x)").toString() //returns Solve(x==-3+17,x)`

What can be a reason for such behaviour? Thanks in advance.
I use symja 1.0.0-SNAPSHOT and android sdk 28.

**Comment by tranleduy2000** [comment]
Could you post whole line of code?

**Comment by wblachowski** [comment]
There's really nothing more than what I posted above. I have an array of equations and I want to evaluate each one in a loop. I based my code on what I found in demos from README but it still doesn't work. I tried using `EvalUtilities` but to no avail. Funnily enough there are some methods which seem to behave properly, e.g `abs`. Below you can find a couple of results I got in debugger:

ExprEvaluator:
![symja1](https://user-images.githubusercontent.com/20361302/57586835-f656ae80-74fb-11e9-9d1f-94a67179fda6.PNG)

EvalUtitlites:
![symja2](https://user-images.githubusercontent.com/20361302/57586837-f656ae80-74fb-11e9-85d2-04fb35557fc8.PNG)

Eval + abs method:
![symja3](https://user-images.githubusercontent.com/20361302/57586838-f656ae80-74fb-11e9-9dbe-1b3202c51d5a.PNG)

**Comment by tranleduy2000** [comment]
I think there is a problem with static initializer. 
You can wait for system inits completely by adding `F.await()`  before calculating.

**Comment by wblachowski** [comment]
Omg, you are right, invoking `F.await()` before performing any calculations solved the issue :) I was not aware of such necessity. Must have overlooked it while going through demos. Thanks!
