### ISSUE TITLE
[Feature request] Shuffle list

### ISSUE THREAD

**Issue by tranleduy2000** [axkr/symja_android_library#141]
For example: 
Shuffle list: `{1,2,3,4,5,6,7,8,9}`

Instead of generating a list of `{key, value}` using `Table({RandomReal(), x}, {x, 1, 9})` function, then sort by keys. I suggest that you should add some functions to help shuffle list easier.

**Comment by axkr** [comment]
Did you try `RandomSample({1,2,3,4,5,6,7,8,9})`

**Comment by tranleduy2000** [comment]
Thanks
