### ISSUE TITLE
Create Fibonacci polynomials

### ISSUE THREAD

**Issue by axkr** [axkr/symja_android_library#143]
Create Fibonacci polynomials:
- https://en.wikipedia.org/wiki/Fibonacci_polynomials

Syntax  `Fibonacci(n,x)`

**Comment by TFranczak** [comment]
This looks like something I'd like to pick up. Currently writing an integer solution

**Comment by axkr** [comment]
The current Fibonacci implementation for integer numbers can be found in line `2020` here 
- https://github.com/axkr/symja_android_library/blob/master/symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/builtin/NumberTheory.java

For the polynomial call the function must be enhanced to allow 2 arguments: `Fibonacci(n,x)`

**Comment by TFranczak** [comment]
Is this expected to return the polynomial itself, or the evaluation of the polynomial for x?

**Comment by axkr** [comment]
It should return the polynomial itself. 

The returned expression will then be evaluated by the evaluation engine.

**Comment by TFranczak** [comment]
Then why is the parameter x required if we're note evaluating for it?

**Comment by axkr** [comment]
For example the user inputs `Fibonacci(3,a)` as an `IAST` ast object

So the ast methods
- `arg1()` returns `3`
- `arg2()` returns  `a`

Then the function should return something (evaluated) like (in Java notation): 
```
  return F.Plus(F.Power(ast.arg2(), F.C3), F.Times(F.C3, ast.arg2()))
```

this expression will then be taken by the evaluation engine and evaluated.
If the user types `Fibonacci(3,8)` instead of a symbolic expression the evaluation engine will evaluate this to `65`

**Comment by axkr** [comment]
The latest comit contains a `lucasLPolynomial()` method, which could be used as a template for the `Fibonacci(n, x)` polynomial:

- https://github.com/axkr/symja_android_library/blob/3cb72ece9f8a44bf3cc0896f5210744e6728f138/symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/builtin/NumberTheory.java#L2458

**Comment by axkr** [comment]
Commit c518539 contains now a much faster iterative `lucasLPolynomialIterative()` method.
