### ISSUE TITLE
CosineDistance({a, b}, {c, d}) doesn't work

### ISSUE THREAD

**Issue by tranleduy2000** [axkr/symja_android_library#144]
![image](https://user-images.githubusercontent.com/19369448/65511203-d8b14100-df00-11e9-8548-befaf34c7831.png)
![image](https://user-images.githubusercontent.com/19369448/65511269-026a6800-df01-11e9-9b7b-f9e63994e7c6.png)

## CosineDistance
```
CosineDistance(u, v)
```
> returns the cosine distance between `u` and `v`.
  
### Examples
```
>> N(CosineDistance({7, 9}, {71, 89}))
7.596457213221441E-5
 
>> CosineDistance({a, b}, {c, d})
1-(a*c+b*d)/(Sqrt(Abs(a)^2+Abs(b)^2)*Sqrt(Abs(c)^2+Abs(d)^2))  
```

## EuclideanDistance
```
EuclideanDistance(u, v)
```

> returns the euclidean distance between `u` and `v`.

See
* [Wikipedia - Euclidean distance](https://en.wikipedia.org/wiki/Euclidean_distance)

### Examples

```
>> EuclideanDistance({-1, -1}, {1, 1})
2*Sqrt(2)

>> EuclideanDistance({a, b}, {c, d})
Sqrt(Abs(a-c)^2+Abs(b-d)^2) 
```

**Comment by axkr** [comment]
Can you do a

```
Clear(b)
```
The variable `b` is probably defined as matrix

![grafik](https://user-images.githubusercontent.com/3109793/65521187-1bffb580-dee9-11e9-9db8-a931091065bd.png)
