### ISSUE TITLE
[BUG] Numerator function gives wrong result in numeric mode

### ISSUE THREAD

**Issue by tranleduy2000** [axkr/symja_android_library#151]
```
>> N(Numerator(Cos(Pi)/Pi))
-0.31831
```

```
>> expr = Numerator(Cos(Pi)/Pi);
>> N(expr)
-1.0
```

**Comment by axkr** [comment]
Numerator picks terms which don‘t have negative exponents.
You have to use Denominator in parallel to get the corresponding result for the denominator.
Maybe add some explanations to markdown?

**Comment by tranleduy2000** [comment]
This problem causes wrong result in other expression like
```
>> N(Int(Sin(x*Pi/3), {x, 1, 2}))
0.15
```
But
```
>> expr = Int(Sin(x*Pi/3), {x, 1, 2});
>> N(expr)
0.95
```

**Comment by axkr** [comment]
Fixed now:
- http://matheclipse.org/input?i=N%28Numerator%28Cos%28Pi%29%2FPi%29%29
