### ISSUE TITLE
How to transpile library to JavaScript

### ISSUE THREAD

**Issue by axkr** [axkr/symja_android_library#154]
What is the best way to transpile this Java library or parts of the library to JavaScript?

These projects are listed to transpile Java to JavaScript
- https://github.com/google/j2cl
- https://github.com/java2script/java2script
- https://github.com/konsoletyper/teavm
- https://github.com/cincheo/jsweet

How can this be automated with Maven or Gradle?

The java7 project may be easier to transpile?
- https://github.com/tranleduy2000/symja_android_library

**Comment by tranleduy2000** [comment]
If these libraries is implemented by using pure Java API, definitely I can port it.

**Comment by axkr** [comment]
@tranleduy2000 which of these tools would you select for creating a library?

I think that we probably have to reduce the size of the Symja library (and package dependency) to use it as a library in JavaScript?

**Comment by axkr** [comment]
I did a test for TeaVM.

Maven get an "Unexpected error occurred: Java heap space" after running TeaVM (0.7.0-dev-906) for over 30 minutes.

**Comment by axkr** [comment]
In the near future we won't use a Java to JavaScript transpiler.
Please open a new issue if interested.
