### ISSUE TITLE
Refactor IntervalSym

### ISSUE THREAD

**Issue by axkr** [axkr/symja_android_library#168]
Refactor IntervalSym:
. https://github.com/axkr/symja_android_library/blob/master/symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/IntervalSym.java

Many functions use a common "base" method:
- coth, csch,...
- sec, csc, tan, cot,...

Unify periodicity and function header usage.
Define common methods for duplicate codes.

Discuss here:
- https://gitter.im/symja_android_library/Lobby

**Comment by OleksandrMariupol** [comment]
Hi axkr. Could you assign me for this issue?)

**Comment by OleksandrMariupol** [comment]
Hi axkr. Could you please specify, some moments. In the task you described: "Many functions use a common "base" method:coth, csch,...sec, csc, tan, cot,..".  For example I find that in  IntervalSym class, only one method  use coth:" public static IAST coth(final IAST ast)". Inside "static IAST coth(final IAST ast)" there are many calls of F.Coth.  This is a small problem, I understood correctly?
Regards,

**Comment by axkr** [comment]
Maybe you can start by simplifying the `for loops' with using BiFunction lambda function:
- https://docs.oracle.com/javase/8/docs/api/java/util/function/BiFunction.html

and see how far you get to extract "common code".

Example:
``` 
                IAST interval = normalize(ast);
		if (interval.isPresent()) {
			try {
				EvalEngine engine = EvalEngine.get();
				IASTMutable result = interval.copy();
				for (int i = 1; i < interval.size(); i++) {
					IAST list = (IAST) interval.get(i);
					IExpr min = list.arg1();
					IExpr max = list.arg2();
>>>>> call BiFunction#apply() here
				}
				return result;
			} catch (RuntimeException rex) {
				//
			}
		}
		return F.NIL;
```

**Comment by OleksandrMariupol** [comment]
Hi axkr. Thanks a lot for your time, the example and link. I have read the info from provided link and many other resources, however I can't understand how using BiFunction in that piece of code will simplify it. How I see it, BiFunction takes two arguments does return the third, but our if else has more then two. This makes me think that I do not understand the requirement. Could you please give me more specifics here?

Regards,

**Comment by axkr** [comment]
I just commited an example in 21f0767

**Comment by OleksandrMariupol** [comment]
Hi axkr. I have one idea. I have created the pull request: https://github.com/axkr/symja_android_library/pull/189/. Сan you please check if this approach is suitable for solving this problem. Thank you very much for your time
