### ISSUE TITLE
Use tablesaw lib for SemanticImport and SemanticImportString

### ISSUE THREAD

**Issue by axkr** [axkr/symja_android_library#169]
Use tablesaw library to implement [SemanticImport](https://github.com/axkr/symja_android_library/blob/master/symja_android_library/doc/functions/SemanticImport.md) and [SemanticImportString](https://github.com/axkr/symja_android_library/blob/master/symja_android_library/doc/functions/SemanticImportString.md) functions:
- https://github.com/jtablesaw/tablesaw

Implement Histogram() function with tablesaw jsplot library
- https://github.com/jtablesaw/tablesaw/tree/master/jsplot

WIP: "Semantic import and Datasets"
- https://github.com/axkr/symja_android_library/blob/master/symja_android_library/doc/20-semantic-import.md

**Comment by hallvard** [comment]
When using tablesaw libraries in Eclipse plugins, I use special "shaded" ones (created during maven build). Shaded libraries in general include all other requires libraries, but in this case certain ones are removed and instead provided using plugin dependencies. This avoids duplicate libraries in the Eclipse installation.

**Comment by axkr** [comment]
The current implementation will be released in 2.0.0. Please open new issue if necessary.
