### ISSUE TITLE
Improve HarmonicNumber for numerical arguments

### ISSUE THREAD

**Issue by axkr** [axkr/symja_android_library#198]
improve HarmonicNumber implementation:
https://github.com/axkr/symja_android_library/blob/master/symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/builtin/Arithmetic.java#L1834

- https://en.wikipedia.org/wiki/Harmonic_number
- https://medium.com/cantors-paradise/the-celebrated-harmonic-numbers-and-how-to-approximate-them-b8747a4efeec

**Comment by dy-eraser** [comment]
Hello there,

Can you please explain this a bit. I might be able to help.

Regards,
Daniel

**Comment by axkr** [comment]
At the moment HarmonicNumber doesn't evaluate for numeric arguments (double and complex values)

In the first step you can improve the commented block starting with:
```
// if (engine.isDoubleMode()) {
...
```

**Comment by axkr** [comment]
The current implementation will be released in 2.0.0. Please open new issue if necessary.
