### ISSUE TITLE
Inequality not working in Solve

### ISSUE THREAD

**Issue by thunderkid** [axkr/symja_android_library#200]
**Describe the bug**
The Solve function is not filtering correctly if an inequality constraint is provided. So
`Solve({x^2 == 4, x > 0}, x, Reals)`
gives
`{{x−>-2},{x−>2}}`
instead of just
`{{x−>2}}`
i.e. it's not handling the `x > 0` correctly. In other situations such as
`Solve({x^2+5x+3==0, x<0}, x)`
it seems to work ok - changing the `x<0` to `x>0` leads to an empty solution set as you'd expect.

**To Reproduce**
I've just tested this on the api testers at http://symjaweb.appspot.com/ and https://symja.org/.

**Expected behavior**
I'd expect it to correctly filter the roots based on any inequalities provided. The second example above shows that it's clearly not just ignoring these constraints. The behavior should be consistent.

(In the case of the complex domain, I'd suggest that for each root and each inequality it should test whether the inequality evaluates to a real expression, and if so should apply it as a filter. But in the case of the domain being explicitly real, there's no ambiguity in what should happen.)

**Java**
Tested against the current web api testers at http://symjaweb.appspot.com/ and https://symja.org/.

**Comment by axkr** [comment]
I think the check for the inequalities should be independent from the given domain.

Please try again. I only updated http://symjaweb.appspot.com/ at the moment.

**Comment by thunderkid** [comment]
Wow, you work fast! Yes, that seems to work ok for all the real cases I've tried.

But for cases with imaginary roots it's still behaving strangely. For example, try
 `Solve({x^2+y^2==5, x+y^2==-7}, {x,y})`
This gives you 4 roots, each with real `x` and imaginary `y`. Filtering these with 
`Solve({x^2+y^2==5, x+y^2==-7, x>0}, {x,y})`
works ok, returning just the roots with `x>0`.

But if you try 
`Solve({x^2+y^2==5, x+y^2==-7, y>0}, {x,y})`
then it selects just two of the roots. This doesn't make much sense, since all the roots had imaginary `y`. I think it should not apply any filter at all in that case, since `>` is undefined over the complex numbers. Perhaps it should even throw an error. That's what I mean about the domain.

However, you can make this well-formulated but still get an incorrect answer:  
`Solve({x^2+y^2==5, x+y^2==-7, i*y<0}, {x,y})`
is well-defined since `i*y` is real for each root, but the answer is incorrect - it gives the empty set `{}` whereas it should return 2 roots.

**Comment by axkr** [comment]
Doesn't seem to be an issue with `Solve()` but with comparing complex symbolic values.

The following expression currently evaluates to `True`which is the main problem:

```
-I*Sqrt(11)>0
```

**Comment by axkr** [comment]
For identifiers with `length==1` Symja distinguishs between lower and upper case. Only upper case `I` is the imaginary unit.
We do this to be more compatible with Mathematica notation, where a single upper case character often implements built-in functionality. Examples:
- https://reference.wolfram.com/language/ref/I.html
- https://reference.wolfram.com/language/ref/D.html
- https://reference.wolfram.com/language/ref/N.html
...

You probably mean:

```
Solve({x^2+y^2==5, x+y^2==-7, I*y<0}, {x,y})
```

**Comment by xwaeaewcrhomesysplug** [comment]
solve({x==y,y>2},{x,y})
{}
solve({x==y,y>2},{x})
{}
Clear(x,y)
Null
solve({x==y,y>2},{y})
{}
>just some extra example here to help your future testing.
solve({x==y,y>2},{x,y})
{},Should be x>2 right?
solve({x==y,y>2},{x})
{}Should be x>2 right?If the variable statement is allowed by the parser.Maybe parser reject then return a more harsh error?

**Comment by axkr** [comment]
The current implementation will be released in 2.0.0. Please open new issue if necessary.
