### ISSUE TITLE
Solve gives error for 1d elastic collision equations

### ISSUE THREAD

**Issue by thunderkid** [axkr/symja_android_library#201]
**Describe the bug**
The following expression:

`Solve({m1 u1^2 + m2 u2^2 == m1 v1^2 + m2 v2^2, m1 u1 + m2 u2 == m1 v1 + m2 v2}, {v1, v2})`

gives the error

`Error: Solve: rule expression (x->y) expected instead of {v2->u2}`

(These equations are for elastic collisions in 1d, representing conservation of energy and momentum.)
If you rearrange them slightly into these forms:

`Solve({m1 u1 + m2 u2 == m1 v1 + m2 v2, u2 - u1 == v2 - v1}, {v1, v2})`
and
`Solve({m1 u1 + m2 u2 == m1 v1 + m2 v2, u2 - u1 == -(v2 - v1)}, {v1, v2})`

Then it gives the correct answers, but it should probably be able to do that from the original form.

**To Reproduce**
Tested on http://symjaweb.appspot.com/.

**Comment by axkr** [comment]
Please try again. I only updated http://symjaweb.appspot.com/ at the moment.

**Comment by thunderkid** [comment]
I tried it again on http://symjaweb.appspot.com/ with the expression
`Solve({m1 u1^2 + m2 u2^2 == m1 v1^2 + m2 v2^2, m1 u1 + m2 u2 == m1 v1 + m2 v2}, {v1, v2})`

It gives incorrect answers. The first root it gives is:
`{v2−>u2,v1−>u1}`
That one is correct. The second one it gives is:
`{v2−>(m2⋅u2−m1⋅u2+2⋅m1⋅u1)/(m2+m1),v1−>u1}`
That one is incorrect for `v1`. It should be
`v1−>(2⋅m2⋅u2−m2⋅u1+m1⋅u1)/(m2+m1)`.
You can get the correct solution from:
`FullSimplify(Solve({m1 u1 + m2 u2 == m1 v1 + m2 v2, u2 - u1 == -(v2 - v1)}, {v1, v2}))`.

(In physics terms the answer it gives has no change in particle1's velocity, which is wrong.)

I'm also finding that sometimes it hangs and gives the message:
`Error: Exception: The API call datastore_v3.Put() was cancelled because the overall HTTP request deadline was reached while waiting for concurrent API calls.`
Even when it runs it seems to take ~10 seconds, which is slower than I'd expect based on other expressions. Perhaps the server is just busy?

**Comment by axkr** [comment]
Can you please test with the browser apps installed locally:
- https://github.com/axkr/symja_android_library/wiki/Browser-apps

**Comment by axkr** [comment]
The current implementation will be released in 2.0.0. Please open new issue if necessary.
