### ISSUE TITLE
Can not define a function with Sum[..]

### ISSUE THREAD

**Issue by fedorkotov** [axkr/symja_android_library#202]
**Describe the bug**
Can not use a function with `Sum[..]` in body

**To Reproduce**
```mathematica
SinSum[n_]:=Sum[Sin[i*x],{i,1,n}];
SinSum[2]
```
Error result:
```
Error: Error in evaluateStringNullPointerException
```

**Expected behavior**

Expected (correct) result expression:
```mathematica
Sin[x]+Sin[2 x]
```

**Additional context**
I'm using https://symjaweb.appspot.com/

**Comment by axkr** [comment]
Cannot reproduce?

![grafik](https://user-images.githubusercontent.com/3109793/98518068-2a389e80-226f-11eb-8a77-8754da32d8e8.png)

**Comment by axkr** [comment]
Ok i can see a `java.lang.NullPointerException` which seems to be related to session handling on the server.

In a fresh session I get the result: Sin[2 `*x]+Sin[x]` as expected.

**Comment by fedorkotov** [comment]
Strange.. I have just reproduced it again.
Maybe this is browser specific? I'm using 64-bit Firefox 82.02 on Windows.

Request to symjaweb.appspot.com was
```
curl "https://symjaweb.appspot.com/ajax/query/" -H "User-Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0" -H "Accept: text/javascript, text/html, application/xml, text/xml, */*" -H "Accept-Language: en-US,en;q=0.5" --compressed -H "X-Requested-With: XMLHttpRequest" -H "X-Prototype-Version: 1.6.0.3" -H "Content-type: application/x-www-form-urlencoded; charset=UTF-8" -H "Origin: https://symjaweb.appspot.com" -H "DNT: 1" -H "Connection: keep-alive" -H "Referer: https://symjaweb.appspot.com/" -H "Cookie:<<SENSITIVE_DATA REMOVED>>" -H "Pragma: no-cache" -H "Cache-Control: no-cache" -H "TE: Trailers" --data-raw "query=SinSum"%"5Bn_"%"5D"%"3A"%"3DSum"%"5BSin"%"5Bi*x"%"5D"%"2C"%"7Bi"%"2C1"%"2Cn"%"7D"%"5D"%"3B"%"0ASinSum"%"5B2"%"5D"
```
Response:
```
{"results":[{"result":null,"line":null,"out":[{"symbol":"General","prefix":"Error","tag":"syntax","text":"<math><mrow><mtext>Error in evaluateStringNullPointerException<\/mtext><\/mrow><\/math>","message":true}]}]}
```

![image](https://user-images.githubusercontent.com/1106650/98519038-48a79580-2281-11eb-9a63-fffe846dccf6.png)

**Comment by fedorkotov** [comment]
Oh, I see. A new attempt in new private browser window was successful.

**Comment by axkr** [comment]
Probably serialization error - `transient`must be removed.
* https://github.com/axkr/symja_android_library/blob/a1bd84107bf5d81f66245fbbf5bc4646d0d97973/symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/patternmatching/RulesData.java#L113

**Comment by axkr** [comment]
In the new release there are these browser apps you can run locally
- https://github.com/axkr/symja_android_library/wiki/Browser-apps
