### ISSUE TITLE
Fix error in `Power#e2ApfloatArg()` method numerical high precision evaluation 

### ISSUE THREAD

**Issue by axkr** [axkr/symja_android_library#207]
Fix error in `Power#e2ApfloatArg()` method numerical high precision evaluation 

ArithmeticException: "Power of negative number; result would be complex" is thrown

See: #206

**Comment by tranleduy2000** [comment]
Using this implementation will reduce the accuracy of apfloat number.
Example:
```Mathematica
N[((2)/(3))*(4-3*Sqrt(2)), 100]

Old version: -0.161760458079523430936710781752729490472677084087229479686692809...
Wolfram:     -0.161760458079523430936710781752729490472677084087229479686692809...

New version: -0.161760458079523192529178585472335853284324913396796799718432944...
                               ^
```

**Comment by axkr** [comment]
Cannot reproduce in current version (line 21114)
https://github.com/axkr/symja_android_library/blob/master/symja_android_library/matheclipse-io/src/test/java/org/matheclipse/io/system/LowercaseTestCase.java
