### ISSUE TITLE
Direct access out in iexpr

### ISSUE THREAD

**Issue by xwaeaewcrhomesysplug** [axkr/symja_android_library#212]
**Is your feature request related to a problem? Please describe.**
I want to directly access the possible solutions like a singular solution.
yes toString&toMMA does work.
But to use result fast in a external code will need to directly obtain info instead of reparse the output.

org.matheclipse.core.interfaces.IExpr;

a=13;b=11;c=12;a+b+c;
Null
a=13;b=11;c=12;d=a+b+c
36
solve({x==y,y==2},{x,y})
{{x->2,y->2}}

As you can see Null,36,can directly be settled in a switch statement,
But getting a unit outcome for a equation need to read,seperate split,map.

**Describe the solution you'd like**
possibly using existing codebase to solve as to not increase function amount and codesize,lol.
Directly return a bulk easy to access data.
Like List<String[]>,or FastutilObject<FastutilObject<char[]>>(to utilize fast util library?).
Any object that can be returned to user to manually query OR simply give this class have ability to return similar info.

**Describe alternatives you've considered**
redefine some functions?Reuse them?(one of those possibly bad idea for forward compatibility)

**Additional context**
This new thing SHOULD never throw exception to not confuse others.
Because main code is generally like:
try{Expr result =e.eval(reusedin);....}catch(EXCEPTION HANDLE FOR THE ENGINE OR EVAL mainly){}

**Comment by axkr** [comment]
Not sure what you would like to achive.

Created this example:
- https://github.com/axkr/symja_android_library/blob/master/symja_android_library/tools/src/main/java/org/matheclipse/core/examples/Issue212.java

The IAST type is some kind of list with a special "Header" element at index 0:
- https://github.com/axkr/symja_android_library/wiki/Class-hierarchy

you can iterate over the arguments from `1..n`

**Comment by xwaeaewcrhomesysplug** [comment]
Thank you very much,i pretty much just solved my problem.
BTW,here is a more generic useful code.

```
public final static java.util.List<String[]> collecresult(org.matheclipse.core.interfaces.IExpr result){
		if (result.isListOfLists()) {
        org.matheclipse.core.interfaces.IAST list = (org.matheclipse.core.interfaces.IAST) result;
		java.util.List<String[]> out=new java.util.ArrayList<String[]>(list.size()-1);
        for (int i = 1; i < list.size(); i++) {
          IExpr arg = list.get(i);
          if (arg.isListOfRules()) {
            org.matheclipse.core.interfaces.IAST listOfRules = (org.matheclipse.core.interfaces.IAST) arg;
			String[] inner=new String[listOfRules.size()-1];
            for (int j = 1; j < listOfRules.size(); j++) {
              org.matheclipse.core.interfaces.IAST rule = (org.matheclipse.core.interfaces.IAST) listOfRules.get(j);
              inner[j-1]=rule.toString();
            }
			out.add(j-1,inner);
          }//other type?
        }
		return out;
      }else if (result.isInteger()) {
        org.matheclipse.core.interfaces.IInteger n = (org.matheclipse.core.interfaces.IInteger) result;
		java.util.List<String[]> out=new java.util.ArrayList<String[]>(1);
		String[] inner=new String[1];
        inner[0]=n.toString();
		out.add(inner);
		return out;
      }//else?
	}
```
