### ISSUE TITLE
[BUG] Give wrong result when calculate integrate of sin, cos function

### ISSUE THREAD

**Issue by tranleduy2000** [axkr/symja_android_library#22]
I want calculate integrate of function ``Int(Sin(x)^3*Cos(x),x)``, but the library give wrong result

![image](https://user-images.githubusercontent.com/19369448/37241418-437db3a6-248b-11e8-86f2-ef1347cdb02b.png)

The result must be ``(sin(x)^4)/4 + C``

![image](https://user-images.githubusercontent.com/19369448/37241431-8051e8ec-248b-11e8-9ada-56f023b8f2f8.png)

**Comment by axkr** [comment]
I cannot reproduce this as a bug with the inverse D() (derivative) function?

```
	public void testGithub22() {
		check("Int(Sin(x)^3*Cos(x),x)", //
				"-Cos(2*x)/8+Cos(4*x)/32");
		check("D(-Cos(2*x)/8+Cos(4*x)/32,x)", //
				"Sin(2*x)/4-Sin(4*x)/8");
		
		// unfortunately Simplify is not sophisticated enough to show this:
		// check("Simplify(Sin(2*x)/4-Sin(4*x)/8)", //
		//    "Sin(x)^3*Cos(x)");

		check("Expand(TrigToExp(Sin(x)^3*Cos(x)))", //
				"(-I*1/16)/E^(I*4*x)(+I*1/8)/E^(I*2*x)-I*1/8*E^(I*2*x)+I*1/16*E^(I*4*x)");
		check("Expand(TrigToExp(Sin(2*x)/4-Sin(4*x)/8))", //
				"(-I*1/16)/E^(I*4*x)(+I*1/8)/E^(I*2*x)-I*1/8*E^(I*2*x)+I*1/16*E^(I*4*x)");
	}
```
