### ISSUE TITLE
Vector/Matrix in the solve method

### ISSUE THREAD

**Issue by parnold-x** [axkr/symja_android_library#222]
Hello, first really great project!

If I try to solve with a vector equation I get a "cannot solve error message"
e.g. simplified
```
Solve({{x,y}=={3,4}},{x,y});
```

Is the support of this planned or am I doing something wrong?

**Comment by axkr** [comment]
The vector format is not directly supported at the moment.

You can write

```
Solve({x==3,y==4},{x,y})
```

**Comment by parnold-x** [comment]
Ok, thank you. Then I will expand the vector equations.

**Comment by axkr** [comment]
Commit 9480355 adds at least the vector input method.
