### ISSUE TITLE
Matrix Expressions Support

### ISSUE THREAD

**Issue by xipengshen** [axkr/symja_android_library#224]
Often I found myself in the need of a full support of Matrix Calculus, where, a matrix or vector can be manipulated as a whole. Such a support exists in Sympy, as illustrated as follows:

>>> X = MatrixSymbol('X', 3, 3)
>>> Y = MatrixSymbol('Y', 3, 3)
>>> (X.T*X).I*Y. // X.T: transpose(X);  X.I: inverse(X)
    𝑋^(−1) (𝑋^𝑇)^(−1) 𝑌     

What would be even better is to support the formulae in Matrix Calculus for differentiations of Matrix expressions (https://en.wikipedia.org/wiki/Matrix_calculus), such as 

                D(transpose(a)*X*b, X) 
       would produce 
               b*transpose(a) 
       where a and b are two vectors and X is a matrix of compatible shapes.

Such a support would make Symja potentially usable in Differentiable Programming.

**Comment by axkr** [comment]
These files need to be improved
- https://github.com/axkr/symja_android_library/blob/master/symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/reflection/system/MatrixD.java
- https://github.com/axkr/symja_android_library/blob/master/symja_android_library/rules/MatrixDRules.m

See:
- http://www.matrixcalculus.org/

**Comment by axkr** [comment]
The current "incomplete" MatrixD implementation will be released in 2.0.0. 
Please open new issue if necessary.
