### ISSUE TITLE
apfloat  1.10.0-SNAPSHOT is no longer available

### ISSUE THREAD

**Issue by JuanVF** [axkr/symja_android_library#226]
Hi! I am using your library, but, it seems that org.apfloat:apfloat:1.10.0-SNAPSHOT is no longer available.  It seems to be replaced by org.apfloat:apfloat:1.10.1-SNAPSHOT. So, I can't build my project because of that.

To reproduce the error you just need to run the project and get this error result:

Error result:

Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find org.apfloat:apfloat:1.10.0-SNAPSHOT.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/apfloat/apfloat/1.10.0-SNAPSHOT/maven-metadata.xml
       - https://dl.google.com/dl/android/maven2/org/apfloat/apfloat/1.10.0-SNAPSHOT/apfloat-1.10.0-SNAPSHOT.pom
       - https://repo.maven.apache.org/maven2/org/apfloat/apfloat/1.10.0-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/org/apfloat/apfloat/1.10.0-SNAPSHOT/apfloat-1.10.0-SNAPSHOT.pom
       - https://oss.sonatype.org/content/repositories/snapshots/org/apfloat/apfloat/1.10.0-SNAPSHOT/maven-metadata.xml
       - https://oss.sonatype.org/content/repositories/snapshots/org/apfloat/apfloat/1.10.0-SNAPSHOT/apfloat-1.10.0-SNAPSHOT.pom
     Required by:
         project :app > org.matheclipse:matheclipse-core:1.0.0-SNAPSHOT:20210406.200228-1098

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Java**
 - Version: Java 8
 - OS : Android

Context: The project is builded in Android Studio 4.0 in Windows 10

**Comment by axkr** [comment]
I added a commit for the `pom.xml`.

Thanks for reporting

**Comment by axkr** [comment]
Sorry forgot to mention, that I'm after a Maven module restructuring now on 2.0.0-SNAPSHOT
