### ISSUE TITLE
Numbers in scientific-notation are not parsed correctly

### ISSUE THREAD

**Issue by HannesWell** [axkr/symja_android_library#227]
**Describe the bug**
For number literal expressions that exceed a certain value the `toScript()` method returns a String representation in scientific notation (for a `org.matheclipse.core.expression.Num` object `toScript()` calles `toString()` which in turn calls `Double.toString()`).

But a `ExprEvaluator` does not parse a correct `IExpr` for such value in scientific notation, even tough toScript() states to return a `"a scripting compatible string representation"`. Instead of parsing the string `"4.3E10"` into a single INumber a product of `4.3` and a variable named `E10` is created.

**To Reproduce**

Example code:
```
import org.matheclipse.core.eval.ExprEvaluator;
import org.matheclipse.core.expression.F;
import org.matheclipse.core.interfaces.INumber;

public class ScientificNotationTest {

	public static void main(String[] args) {
		double largeNumber = 4.3e10;
		INumber number = F.num(largeNumber);
		ExprEvaluator exprEvaluator = new ExprEvaluator();

		System.out.println(number.toScript());
		System.out.println(exprEvaluator.parse(Double.toString(largeNumber)));
		System.out.println(exprEvaluator.parse(number.toScript()));
	}
}
```

Error result:

```
4.3E10
4.3*e10
4.3*e10
```

**Expected behavior**
It is expected that the String returned by IExpr.toScript() can be parsed by an `ExprEvaluator` and creates an equivalent AST.
Since the scientific notation can be very handy I suggest to adjust the parser to process scientific notation correctly instead of changing the return value toString()/toScript() of `Num`.

Expected (correct) result expression:

```
4.3E10
4.3E10
4.3E10
```

**Java**
 - Version 11
 - OS: Windows 10

**Comment by HannesWell** [comment]
Regarding my suggestion to adjust the parser I just found issue #54. So I assume this is not an option.

In this case I think it should be the other way round that toScript() returns a String in "default" notation, at least if `Config.EXPLICIT_TIMES_OPERATOR=false`. For toString I think it is better to stick with Double.toString() because the String representation is then more readable.

**Comment by axkr** [comment]
Yes with setting `FEConfig.EXPLICIT_TIMES_OPERATOR = true;` at the beginning your example will work.

But you're right, because we want to keep compatibility with Mathematica input syntax the behaviour of the `toString()` method is ambigous. 
I'm thinking about to make the output dependent on `FEConfig.EXPLICIT_TIMES_OPERATOR`.


```
public class ScientificNotationTest {

  public static void main(String[] args) {
    FEConfig.EXPLICIT_TIMES_OPERATOR = true;
    double largeNumber = 4.3e10;
    INumber number = F.num(largeNumber);
    ExprEvaluator exprEvaluator = new ExprEvaluator();

    System.out.println(number.toScript());
    System.out.println(exprEvaluator.parse(Double.toString(largeNumber)));
    System.out.println(exprEvaluator.parse(number.toString()));
  }
}
```

**Comment by axkr** [comment]
Please test if  e10e077 is OK for you.

**Comment by HannesWell** [comment]
Yes that commit looks good to me. Thanks.
