### ISSUE TITLE
Add eclipse-config files to .gitignore and unify gitignore files

### ISSUE THREAD

**Issue by HannesWell** [axkr/symja_android_library#228]
In order to simplify developing symja in Eclipse IDE I suggest to ignore Eclipse project configuration files like `.project`, `.classpath` and the `.settings` folder in git, as well as Maven's target folder. The mentioned files/folders are generated by Eclipse when you import the symja projects from git into an Eclipse workspace or build symja with Maven.

Besides that the .gitignore files of the sub-modules contain redundant entries which could be added to the root .gitignore and would make the sub .gitignores obsolete.

If you agree I can provide a PR with corresponding changes.

**Comment by axkr** [comment]
Yes, please provide a PR

**Comment by HannesWell** [comment]
> Note I added github actions:
> 
>     * https://github.com/axkr/symja_android_library/actions
> 
> 
> but currently having problems with copying the *.JAR to staging:
> 
>     * https://github.community/t/maven-cp-target-jar-staging/183191
> 
> 
> Maybe you can also help there.

Sure, I can have a look at it.
