### ISSUE TITLE
Limit((Sqrt(((t+4)*(t-2)^4))/((3*t)-6)^2),t->2) causes infinited loop.

### ISSUE THREAD

**Issue by tranleduy2000** [axkr/symja_android_library#230]
```
Limit((Sqrt(((t+4)*(t-2)^4))/((3*t)-6)^2),t->2) 
```
![image](https://user-images.githubusercontent.com/19369448/120919522-46f16380-c6e4-11eb-9d0c-f5657a50a152.png)

Wolfram|Alpha result: 
![image](https://user-images.githubusercontent.com/19369448/120919534-5670ac80-c6e4-11eb-8028-f9e61f5a504d.png)

**Comment by axkr** [comment]
To avoid the endless loop you can reduce the `LIMIT_LHOSPITAL_RECURSION_LIMIT` to `16`
```
  public static int LIMIT_LHOSPITAL_RECURSION_LIMIT = 16;
```
