### ISSUE TITLE
[BUG] MatrixRank({{1,2,3,4,5},{2,4,6,8,11},{3,6,9,12,14},{4,8,12,16,20}}) returns wrong result.

### ISSUE THREAD

**Issue by tranleduy2000** [axkr/symja_android_library#232]
```
MatrixRank({{1,2,3,4,5},{2,4,6,8,11},{3,6,9,12,14},{4,8,12,16,20}})
```

![image](https://user-images.githubusercontent.com/19369448/121083651-e65c4680-c809-11eb-9f69-8f7cd8150348.png)

Expected result: `2`

![image](https://user-images.githubusercontent.com/19369448/121083596-d6446700-c809-11eb-8eec-b34aa4ce79a5.png)

**Comment by axkr** [comment]
This depmeds on wrong `RowReduce`

```
 RowReduce({{1,2,3,4,5},{2,4,6,8,11},{3,6,9,12,14},{4,8,12,16,20}})
```
