### ISSUE TITLE
Unit-test failures and some Unit-Tests are not executed tests in workflow

### ISSUE THREAD

**Issue by HannesWell** [axkr/symja_android_library#234]
**Describe the bug**

When executing the build locally on Windows 10 using a Java-11 JDK the tests `TestPods.testListPlot002`  and `TestPodsStrict.testListPlot002` are failing.

When looking at the tests I recognized that they are only executed on a Windows platform.
But the workflow actions of Symja are executed in a Linux VM, therefore those tests are skipped during that workflow builds.
This is probably the reason why those failures remained unrecognized.

The console print-out of `Building matheclipse-api 2.0.0-SNAPSHOT`  shows that those tests are skipped:
```
 -------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.matheclipse.api.TestPods
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Tests run: 45, Failures: 0, Errors: 0, Skipped: 44, Time elapsed: 2.701 sec
Running org.matheclipse.api.TestFuzzyInput
Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.447 sec
Running org.matheclipse.api.TestPodsStrict
InputError(errorCode=TTEG04,slice=FrozenSlice(range=[4,5), value='#'),arguments=[])
Tests run: 39, Failures: 0, Errors: 0, Skipped: 22, Time elapsed: 0.916 sec

Results :

Tests run: 94, Failures: 0, Errors: 0, Skipped: 66
```

**Expected behavior**
In order to ensure all tests working and of course the tested classes are working, I suggest to either make the tests platform independent or to run the workflow build on a Windows VM instead of linux.

Within the skipped tests windows line ending are hard-coded into the expected result string. Is the line-ending the only thing that make the tests not work on linux?
If yes, those tests can be made platform independent easily by using `System.lineSeparator()`.
In this case instead of writing something like this:
```
@Test
public void test() {
	String results = ""; /* Compute actual result */
	assertEquals(results,
		" expected Line\r\n" 
	    + " nextLine");
}
```
I suggest to use:
```
private static final String NL = System.lineSeparator();

@Test
public void test1() {
	String results = ""; /* Compute actual result */
	assertEquals(results,
		 " expected Line" + NL 
	     + " nextLine");
}
```
or 

```
@Test
public void test2() {
	String results = ""; /* Compute actual result */
	assertEquals(results, 
		String.join(System.lineSeparator(),
		 " expected Line", 
		" nextLine"));
}
```

If you agree I can submitt a corresponding PR.

**Java**
 - Version [Java 11]
 - OS [Windows 10,...]

**Comment by axkr** [comment]
The pretty print format for JSON was only used for simpler human control.
So I would prefer a simple normalizing of the message:

```
  public static String toPrettyStringNormalizingNewline(ObjectNode messageJSON) {
    return messageJSON.toPrettyString().replaceAll("\\r\\n", "\n");
  }


final String jsonStr = toPrettyStringNormalizingNewline(messageJSON);

    assertEquals(
        jsonStr, //
...



...
```

Should I commit this solution?

**Comment by HannesWell** [comment]
> The pretty print format for JSON was only used for simpler human control.
> So I would prefer a simple normalizing of the message:
> 
> ```
>   public static String toPrettyStringNormalizingNewline(ObjectNode messageJSON) {
>     return messageJSON.toPrettyString().replaceAll("\\r\\n", "\n");
>   }
> 
>   @Test
>   public void testSyntaxError001() { 
>     ObjectNode messageJSON = TestPods.createJUnitResult("?#?", formatsTEX);
>    final String jsonStr = toPrettyStringNormalizingNewline(messageJSON);
> 
>     assertEquals(
>         jsonStr, //
> ```
> 
> Should I commit this solution?

This is also a good solution.
I've already started to work on it. At the moment it looks like there are some more problems.
So I can implement your solution.

Should I create a PR so you can review it or should I push it directly?

**Comment by axkr** [comment]
I commited my solution.

**Comment by HannesWell** [comment]
Thanks. Do you also take care about the failing tests or should I ?
For the failing `testListPlot002()` tests the least significant digits have changed so the values have to be updated.
For the other failures it is again a \r\n vs. \n problem but I think in an escaped manner.

**Comment by axkr** [comment]
See commit message. 
Do you know a simple solution for least significant digits in unit test strings?

IMO it's not worth to do a "big workaroud" only to fullfill the tests.

**Comment by HannesWell** [comment]
Thanks! Now all tests are working, even on my Windows computer. Now I can continue with improving the Maven pom structure. 

> Do you know a simple solution for least significant digits in unit test strings?
> 
> IMO it's not worth to do a "big workaroud" only to fullfill the tests.

I found a not to complicated solution that can treat least significant figures in the tests and does not require modification of main-sources. I've opened #235 for this.
