### ISSUE TITLE
Solve gives wrong output.

### ISSUE THREAD

**Issue by xwaeaewcrhomesysplug** [axkr/symja_android_library#247]
It gives the wrong ans

working prove for math,
k+3/4=k/2
2k+6=4k
6=2k

correct,3
wrong,-3/2

**To Reproduce**

Example input Symja input expression:

```
>> Solve(k+3/(4)==(k)/2,{k})
```

Error result:-3

```

```

**Expected behavior**

Expected (correct) result expression:3

```

```

==

**Java**
 - Java15
Win10

**Comment by axkr** [comment]
If you set the paranthesis you get the expected result:

```
>> Solve((k+3)/(4)==(k)/2,{k})
{{k->3}}

>> Solve(k+3/(4)==(k)/2,{k})
{{k->-3/2}}
````

**Comment by xwaeaewcrhomesysplug** [comment]
ahhh sorry you are right.will note this down.
