### ISSUE TITLE
"Overflow occurred in computation" and incorrect results for solving a cubic equation with scalar with many digits

### ISSUE THREAD

**Issue by HannesWell** [axkr/symja_android_library#261]
**Describe the bug**
When solving a cubic equation that contains a scalar value with too many digits Symja prints "General: Overflow occurred in computation." very often and the result is incorrect.
As you can see from the example below, if the number of digits after the comma is below a certain threshold the error messages vanish and the result becomes correct.
The example was derived from a more complex case and is crafted to have only a minimal difference. If more digits are added the behaviour stays the same.

I don't know the root of the problem, but my first impression would be that Symja should simply discard digits that it cannot handle instead of failing to compute a result?

**To Reproduce**
Example input Symja input expression:

```
>> Solve(0.0000424413181578 == x^3 , x)

>> Solve(0.00004244131815783 == x^3 , x)
```

Error result:

```
<< {{x->-0.017440795598675105+I*0.030208344101328947},{x->0.034881591197350216},{x->-0.01744079559867511+I*(-0.03020834410132894)}}

<< General: Overflow occurred in computation.
<< General: Overflow occurred in computation.
<< General: Overflow occurred in computation.
<< General: Overflow occurred in computation.
<< General: Overflow occurred in computation.
<< {{x->0.034881591197364697},{x->0.034881591197364697*(-1)^0.66666666666666666},{x->(-0.0018522195911839047)*(-6679)^0.33333333333333333}}

```

The following Java-code snippet gives the same result:
```
	public static void main(String[] args) {
		String input3 = "Solve(0.0000424413181578 == x^3 , x)";
		String input4 = "Solve(0.00004244131815783 == x^3 , x)";

		ExprEvaluator exprEvaluator = new ExprEvaluator();
		System.out.println(exprEvaluator.eval(input3));
		System.out.println(exprEvaluator.eval(input4));
	}
```

**Expected behavior**

Wolfram-Alpha gives the following results:
```
Input interpretation
solve 0.00004244131815783 = x^3 for x

Results
x = -0.0174408 - 0.0302083 i
x = -0.0174408 + 0.0302083 i
x = 0.0348816

```
Expected (correct) result expression:

```
<< {{x->-0.017440795598675105+I*0.030208344101328947},{x->0.034881591197350216},{x->-0.01744079559867511+I*(-0.03020834410132894)}}

<< {{x->-0.017440795598675105+I*0.030208344101328947},{x->0.034881591197350216},{x->-0.01744079559867511+I*(-0.03020834410132894)}} ( might vary slightly)

```

**Java**
 - Version [Java-11]
 - OS [Windows 10]

**Comment by HannesWell** [comment]
It is interesting that symja can successfully compute a result without errors for both equations if a power of two or four is used in the equation. For exponents 5, 6 and seven the result is similar to the initial case where only the first equation can be solved.

**Comment by axkr** [comment]
>  For exponents 5, 6 and seven the result is similar to the initial case where only the first equation can be solved.

Can you send some examples?

**Comment by HannesWell** [comment]
> 
> 
> > For exponents 5, 6 and seven the result is similar to the initial case where only the first equation can be solved.
> 
> Can you send some examples?

Sure:

```
>> Solve(0.0000424413181578 == x^2 , x)
>> Solve(0.00004244131815783 == x^2 , x)
>> Solve(0.0000424413181578 == x^4 , x)
>> Solve(0.00004244131815783 == x^4 , x)
>> Solve(0.0000424413181578 == x^5 , x)
>> Solve(0.00004244131815783 == x^5 , x)
>> Solve(0.0000424413181578 == x^6 , x)
>> Solve(0.00004244131815783 == x^6 , x)
>> Solve(0.0000424413181578 == x^7 , x)
>> Solve(0.00004244131815783 == x^7 , x)
```
I have not verified if the returned results are correct and only checked if the error message is printed.
When a exponent of 5, 6 or 7 is used the second equation of the pairs (the one with one more digit) prints the mentioned error message.

**Comment by axkr** [comment]
With commit c3ca677 the Apfloat `Power()` computation switches to complex computation, if the base is a negative number.

**Comment by HannesWell** [comment]
Great. Thanks!
The case `exponent.complexSign() < 0` is not relevant anymore?

**Comment by axkr** [comment]
> The case `exponent.complexSign() < 0` is not relevant anymore?

It`s the same logic as here:
https://github.com/axkr/symja_android_library/blob/c3ca677ca89b99bfdcfb0ec209584fc628ff60a0/symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/builtin/Arithmetic.java#L3711

**Comment by HannesWell** [comment]
Understand that. Thanks.
