### ISSUE TITLE
How to get consistently the raw value given equation or some mathematical representation.

### ISSUE THREAD

**Issue by xwaeaewcrhomesysplug** [axkr/symja_android_library#266]
like eg,assume out is two decimal places
3^(1/4)
>1.31

what i know is that sometimes it calculate sometimes it doesn't
eg
2^(0.5)
>1.4142135623730951
in this case it does calculate the value to some decimal places.

Does symja have existing function that does that?

**Comment by axkr** [comment]
Do you mean to get always a numerical value through a function:
- https://github.com/axkr/symja_android_library/blob/master/symja_android_library/doc/functions/N.md

```
N(3^(1/4))
```

Or if you know, you always get a double value result from your input:
- https://github.com/axkr/symja_android_library/blob/39793ada8279d0984d78f07d52160f26808bc1c3/symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/eval/ExprEvaluator.java#L578

**Comment by xwaeaewcrhomesysplug** [comment]
huge thanks you even added an api.Though in my use case it is not really needed.I probably prefer just adding N(). Huge thanks.closing this.
