### ISSUE TITLE
Integration wrong in ln and 1/x

### ISSUE THREAD

**Issue by xwaeaewcrhomesysplug** [axkr/symja_android_library#269]
**Describe the bug**
Integration 1/x basic propeties gives wrong output.

**To Reproduce**

Example input Symja input expression:

```
>> 
D(Ln(x),x)
1/x
Integrate(1/x,x)
Log(x)
```

Error result:

```
Integrate(1/x,x)
Log(x)
```

**Expected behavior**

Expected (correct) result expression:

```
Integrate(1/x,x)
Ln(x)
```

**Java**
Java15,win10

**Additional context**
other integration test ok.

**Comment by tranleduy2000** [comment]
Log(x) is Ln(x)

**Comment by axkr** [comment]
We are using the same conventions as Mathematica for the `Log` function:
- https://reference.wolfram.com/language/ref/Log.html

So there is no '`Ln` function but only `Log` function for the natural logarithm.

Note that `Log(a,b)` is converted to `Log(b)/Log(a)`
