### ISSUE TITLE
Leverage Loggers to report warnings and errors

### ISSUE THREAD

**Issue by HannesWell** [axkr/symja_android_library#272]
At many places in the codebase of Symja 

- `System.out` or `System.err` PrintStream is used to report error-messages and exceptions.
- The method `EvalEngine.printMessage()` is used for this purpose as well. While one method prints the message to the EvalEngine's error PrintStream and emits a logger warning, the other overload only prints the assembled message to the error PrintStream.
- `Exception.printStacktrace()` is used to print messages

In all of those cases the class that encountered the error should use their own logger instead and report a warning or error as appropriated.
This allows users of Symja to control better where those messages are processed in the end. E.g. at the moment errors are printed twice if the loggers are configured to print on the console and an issue is reported via `EvalEngine.printMessage()`.

Furthermore the flag `Config.DEBUG` should not be used to enable or disable debug logging. Instead the logger.debug() should be called. Then the user can set the corresponding logger level as desired (either globally or per namespace). 

I can prepare a PR for this.

**Comment by axkr** [comment]
Yes if you like please create a PR. 
Note that `IOFunctions.printMessage(...)` is printed in red in the web interface: 

![image](https://user-images.githubusercontent.com/3109793/132699869-21954b75-7f8d-4c78-8578-01ae88fe7146.png)

**Comment by HannesWell** [comment]
Is EvalEngine's flag `fThrowError` required? It is only used in `ListFunctions.Total` (where it is set to true), but without deep knowledge it seems to be a bit arbitrary that it is used there but nowhere else. Especially because a potential Exception is catched immediately. Wouldn't it be better (if possible) to check directly if the evaluated `IExpr temp` is valid?

If so we could remove the flag `fThrowError` and its getters and setters. Then calling EvalEngine.printMessage() could be replaced by a logger in those cases where an erroneous state or a warning should be logged. This way the callers can specify more precisely what is logged and at which level (e.g. warning or error?) A.t.m. everything is logged as warning plus is printed to the error stream. My goal is that a message is logged once and the log4j configuration specifies what happens then, this way users can use their own specification.

Log4j-core can also be set up to print errors to the `SYSTEM_ERR` stream which should print error messages in red.

I think the reason why log messages are not printed to the console at the moment is that the log4j2.properties is not picked up by log4j-core, so it takes its default configuration where only errors are written to the console (but printMessage writes warnings).

**Comment by axkr** [comment]
> Is EvalEngine's flag `fThrowError` required? It is only used in `ListFunctions.Total` (where it is set to true), but without deep knowledge it seems to be a bit arbitrary that it is used there but nowhere else. Especially because a potential Exception is catched immediately. Wouldn't it be better (if possible) to check directly if the evaluated `IExpr temp` is valid?

we can do this change, if we comment the test in `LowercasTestcase#testTotal()` and open another issue where I c an solve the unit test lkater. This case has to be checked with an other implementation the fThrowError is not suitable.

```
//check(
//        "Total( {{1, 2, 3}, {4, 5}, {6}})", //
//        "Total({{1,2,3},{4,5},{6}})");
```

**Comment by HannesWell** [comment]
When using loggers the configuration flags `org.matheclipse.core.basic.Config.DEBUG` and `org.matheclipse.core.basic.Config.SHOW_STACKTRACE` can be made obsolete.
Instead of those flags the debug print-out or the exceptions should be logged at level debug (info would be possible as well).

**Comment by axkr** [comment]
> 
> When using loggers the configuration flags `org.matheclipse.core.basic.Config.DEBUG` and `org.matheclipse.core.basic.Config.SHOW_STACKTRACE` can be made obsolete.
> Instead of those flags the debug print-out or the exceptions should be logged at level debug (info would be possible as well).

Yes that will be the correct way. Using the Config flags was always the quick and dirty way to see if an exception occurs during execution.

**Comment by HannesWell** [comment]
Exactly. As I have written in PR #278 (I just add it here again for the record) my intention is that there are only logging messages are used in Symja to report information to the user. The goals is to remove all usages of System.out/err or Throwable.printStacktrace()) (except for things like OutputStreamExpr).

We can then configure the logger used by Symja to behave the same way as it is behaving now, i.e. to print only errors to the user as you have mentioned above. It could also be considered to write a log file with lower level messages as well.
The good thing about it is that each user of Symja can use it's own fine-tuned configuration. For example in our product we want to write all log messages to the Eclipse Error-Log view and don't want to write anything to the console.

**Comment by HannesWell** [comment]
Closed this unintentionally.
