### ISSUE TITLE
Custom function not working.

### ISSUE THREAD

**Issue by tranleduy2000** [axkr/symja_android_library#28]
See this image. First, it give correct result.  But when I recalculate, it give zero result.

![image](https://user-images.githubusercontent.com/19369448/38137667-3956019c-3450-11e8-9dfb-f16935625c08.png)

**Comment by tranleduy2000** [comment]
Could you fix it?

**Comment by axkr** [comment]
At the first time you set the global Variable x=2. At the Second time you calculate NDerivative(2^2, 2) which gives 0.

**Comment by tranleduy2000** [comment]
Thanks for your suggestion. It worked.
