### ISSUE TITLE
Calc of matrix in multiplication.output structure

### ISSUE THREAD

**Issue by xwaeaewcrhomesysplug** [axkr/symja_android_library#284]
**Describe the bug**
i am not sure but i think https://en.wikipedia.org/wiki/Matrix_multiplication the illustration section
also shows the properties of expanding dimension.

**To Reproduce**
my exec
{{-4},{3}}*{-6,5}
{{24},{15}}

Just In case i also tried Cross function
Cross({{-4},{3}},{-6,5})
Cross({{-4},{3}},{-6,5})<?welcome back^_^

The output should be a 2x2 matrix.right?
{}
{}x{}{}
=
{}{}
{}{}

The expected result should probably be.
{{-4},{3}}*{-6,5}
{{24,-20},{-18,15}}

**Java**
 - Version Java 15
 - OS  Windows 10

**Comment by axkr** [comment]
I don`t understand.

Do you mean multiplication of a 2x1 matrix with 1x2 with the `. ` operator?

```
>> {{24},{15}}.{{24,15}}
{{576,360},{360,225}}
```

**Comment by xwaeaewcrhomesysplug** [comment]
ah yes.I think i know why mine failed.

{{-4},{3}}.{-6,5}
Dot: inconsistent dimensions: 2 != 1
{{-4},
 {3}}.{-6,5}
{{-4},{3}}.{{-6,5}}
{{24,-20},
 {-18,15}}

It seems that I need to give the second matrix one more bracket.
I suspect it is because it will treat it as vector?if not given bracket.
