### ISSUE TITLE
[Feature request] * (Multiply operator) for matrix

### ISSUE THREAD

**Issue by tranleduy2000** [axkr/symja_android_library#29]
Could you add an option for multiply operator as dot product with matrix term.

Example I want to calculate dot product of two matrix 
```
{{1,2},{3,4}} . {{1,2,3},{4,5,6}} = {{1,2},{3,4}} * {{1,2,3},{4,5,6}}
```

**Comment by axkr** [comment]
The [Dot operator '.'](https://github.com/axkr/symja_android_library/blob/master/symja_android_library/doc/functions/Dot.md) should do vector and matrix multiplications: `{{1,2},{3,4}} . {{1,2,3},{4,5,6}}`.

With the [MatrixPower](https://github.com/axkr/symja_android_library/blob/master/symja_android_library/doc/functions/MatrixPower.md) you can calculate a matrix to a given power.

Other linear algebra functions are listed [here](https://github.com/axkr/symja_android_library/blob/master/symja_android_library/doc/linear-algebra.md):
