### ISSUE TITLE
Inverse hyperbolic functions are usually called "area functions"

### ISSUE THREAD

**Issue by HannesWell** [axkr/symja_android_library#292]
**Describe the bug**

Unlike the inverse of ordinary trigonometric functions (like `sin`, `cos`, ...) that are usually called [arcus functions](https://en.wikipedia.org/wiki/Inverse_trigonometric_functions) the inverse functions of the hyperbolic functions (like `sinh`, `cosh`, ...) are usually called [area functions](https://en.wikipedia.org/wiki/Inverse_hyperbolic_functions#Inverse_hyperbolic_sine).

Therefore the mathematical symbol is usually the name of the corresponding hyperbolic function prefixed with `ar-`, for trigonometric functions it is usually `arc-`. Unfortunately Symja also uses the `arc-` prefix for the inverse hyperbolic functions which does not comply with the usual mathematical notation.
The Symbols in class `S`, the corresponding factory methods in class `F` and the evaluator classes in `ExpTrigsFunctions` should be renamed the following way:

- `ArcSinh` -> `ArSinh`
- `ArcCosh` -> `ArCosh`
- `ArcTanh` -> `ArTanh`
- `ArcCoth` -> `ArCoth`
- `ArcSech` -> `ArSech`
- `ArcCsch` -> `ArCsch`

I hope I did not forget any location.

**Comment by axkr** [comment]
The Symja functions names are compatible with the Mathematica names.

For example:
- https://reference.wolfram.com/language/ref/ArcSinh.html
- https://reference.wolfram.com/language/ref/ArcCsch.html

For this reason the general renaming should be avoided.

There are however already existing aliases which could be extended:
- https://github.com/axkr/symja_android_library/blob/196a834b1b3ad936fb938046d375bbeff74d7ea4/symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/convert/AST2Expr.java#L1430

**Comment by HannesWell** [comment]
OK, understand that.
Since we use Symja directly from code and not via the notebooks the aliases do not affect us (or am I wrong with the assumtion that they are only considered by the parser). If the notebook language is intended to be Mathematica compatible it could be done the other way round: Name the methods and classes like the usual convention and add aliases for the Mathematica names.

However this is just cosmetic and has no functional advantage because the intention of the methods is clear how they are, even it is not the usual (at least what Wikipedia says) mathematical convention.

**Comment by axkr** [comment]
Yes the aliases are used in the parsers.

**Comment by hakanai** [comment]
More often than not, in code, the prefix for these is just `a-`.

**Comment by axkr** [comment]
> More often than not, in code, the prefix for these is just `a-`.

Yes the ALIASES_STRINGS  are named like this
