### ISSUE TITLE
[Feature request] Degree (angle) unit output

### ISSUE THREAD

**Issue by tranleduy2000** [axkr/symja_android_library#30]
Could you add an option for angle unit output, such as Radian, Degree and Grad
Example I want to calculate ``ArcSin(1)`` in degree mode, it will give result as ``90``

**Comment by axkr** [comment]
You can try `N(ArcSin(1)*Degree)` to get a numerical result.

But currently there is no Quantity system implemented.
There is an implementation in the [Tensor project](https://github.com/idsc-frazzoli/tensor/tree/master/src/main/java/ch/ethz/idsc/tensor/qty) which could be ported to Symja.
