### ISSUE TITLE
[BUG] Rationalize not give simplify result [ArcCos(-Rationalize(0.5))]

### ISSUE THREAD

**Issue by tranleduy2000** [axkr/symja_android_library#31]
See this image
![image](https://user-images.githubusercontent.com/19369448/38424135-43bc251e-39da-11e8-8f4b-3cdbef7867d5.png)

**Comment by axkr** [comment]
With  the [Rationalize](https://github.com/axkr/symja_android_library/blob/master/symja_android_library/doc/functions/Rationalize.md)
