### ISSUE TITLE
statistics T test

### ISSUE THREAD

**Issue by xwaeaewcrhomesysplug** [axkr/symja_android_library#320]
**Is your function or algorithm new to our collection.**
Probably yes?

**Describe the solution you would like to provide**
just implement it as a function maybe named ttest?
reference,https://en.wikipedia.org/wiki/Student%27s_t-test

- what should the new function signature look like?
Ttest(mean,hypothesismean,estimatestddev,pupulation mean)

- is your function or algorithm implemented in an open source library?
possibly yes in numpy or scipy probably yes.

- how can a converter from and to the libraries used internal format be created?
there are only four input they are commonly float,i believe.Probably not double.but may overload the function,why not?

ps,just a suggestion.Possibly useless??But idk.I somehow see it in some academic use.Not much of a practical use.

**Comment by axkr** [comment]
The current implementation will be released in 2.0.0. Please open new issue if necessary.
