### ISSUE TITLE
Delete symbols S.$RealVector, S.$RealMatrix

### ISSUE THREAD

**Issue by axkr** [axkr/symja_android_library#325]
To let the types:

-  `org.matheclipse.core.expression.ASTRealVector` and
-  `org.matheclipse.core.expression.ASTRealMatrix`

look transparently inside the programming API as ordinary vectors (list of `double` values) and matrices (list of lists of `double`values) their header should be set to `S.List`and
the symbols `S.$RealVector, S.$RealMatrix` should be deleted.

**Comment by HannesWell** [comment]
That remembers me a long standing question I have:
Can I define and use a Vector/Matrix of Expressions in Symja? For example something like

| a  b |      | sin(x)  cos(y) |     | sin(x)  cos(y) |
| c  d |   = | cos(z) tan(zz)|  * | cos(z) tan(zz)|

that then can be evaluated to the corresponding matrix multiplication.
I tried it on https://matheclipse.org/ some time ago but I did not manage to make it work.

**Comment by axkr** [comment]
> Can I define and use a Vector/Matrix of Expressions in Symja?

the Dot operatpr . can be used for matrix multiplication:
- https://github.com/axkr/symja_android_library/blob/master/symja_android_library/doc/functions/Dot.md

**Comment by HannesWell** [comment]
> 
> 
> > Can I define and use a Vector/Matrix of Expressions in Symja?
> 
> the Dot operatpr . can be used for matrix multiplication:
> 
>     * https://github.com/axkr/symja_android_library/blob/master/symja_android_library/doc/functions/Dot.md

Thanks for that hint!
