### ISSUE TITLE
Integrate[x * (1/2*Pi - ArcSin[x]), {x, 0, 1}] returns wrong result.

### ISSUE THREAD

**Issue by tranleduy2000** [axkr/symja_android_library#330]
Given the input
```mma
Integrate[x * (1/2*Pi - ArcSin[x]), {x, 0, 1}]
```
![image](https://user-images.githubusercontent.com/19369448/143669503-959dbc48-c2d9-4a32-956c-723e8106b7d5.png)

The answer should be
![image](https://user-images.githubusercontent.com/19369448/143669510-643cf4fc-9495-44c1-82e8-cdbf5ceb297c.png)

**Comment by tranleduy2000** [comment]
I tried with Wolfram|Alpha, this calculation is wrong because the `Limit` function returns wrong result.

1. Symja console 
![image](https://user-images.githubusercontent.com/19369448/143669816-c4f53e8e-8586-46b5-b5ac-f312209e9aef.png)

2. Wolfram|Alpha
![image](https://user-images.githubusercontent.com/19369448/143669799-8757445c-4cfb-4908-8312-e5bb5cf5cac8.png)

**Comment by tranleduy2000** [comment]
In `SeriesFunctions.java`
```Java
        if (timesPolyFiltered[0].size() > 1 && timesPolyFiltered[1].size() > 1) {
          IExpr first = engine.evaluate(data.limit(timesPolyFiltered[0].oneIdentity1()));
          IExpr second = engine.evaluate(data.limit(timesPolyFiltered[1].oneIdentity1()));
          if (first.isReal() || second.isReal()) {
            IExpr temp = engine.evaluate(F.Times(first, second));
            if (!temp.isIndeterminate()) {
              return temp;
            }
            if (data.limitValue().isZero()) {
              // Try reciprocal of symbol and approach to +/- Infinity
              IExpr newTimes = timesAST
                  .replaceAll(F.Rule(data.variable, F.Power(data.variable, F.CN1)));
              if (newTimes.isPresent()) {
                IAST infinityExpr = (data.direction == Direction.FROM_BELOW) ? F.CNInfinity
                    : F.CInfinity;
                LimitData copy = new LimitData(data.variable, infinityExpr,
                    F.Rule(data.variable, infinityExpr), data.direction);
                temp = engine.evaluate(copy.limit(newTimes));
                if (!temp.isIndeterminate()) {
                  return temp;
                }
              }
            }
          }
        }
```

The `first` variable is `0`
The `second` variable is `Limit(1/Sqrt(1-x^2),x->1,Direction->1)-Limit(ArcTan(x/Sqrt(1-x^2)),x->1,Direction->
1)+Infinity*Limit(ArcTan(x/Sqrt(1-x^2)),x->1,Direction->1)` => `Indetermine`

But the expression `IExpr temp = engine.evaluate(F.Times(first, second));` returns `0` => incorrect result.

**Comment by axkr** [comment]
> I tried with Wolfram|Alpha, this calculation is wrong because the `Limit` function returns wrong result.
> 
>     1. Symja console
>        ![image](https://user-images.githubusercontent.com/19369448/143669816-c4f53e8e-8586-46b5-b5ac-f312209e9aef.png)
> 
>     2. Wolfram|Alpha
>        ![image](https://user-images.githubusercontent.com/19369448/143669799-8757445c-4cfb-4908-8312-e5bb5cf5cac8.png)

Could you please replace the images with "source code text".

**Comment by axkr** [comment]
The expression

```
Integrate(x*(1/2*Pi-ArcSin(x)),x)
```

should return 
```
(Pi*x^2)/4 - (1/4)*x*Sqrt(1-x^2) + ArcSin(x)/4 - (1/2)*x^2*ArcSin(x)
```

when it would be much easier to calculate the `Limit`

Unfortunately the Rubi engine returns with denominators calculating to `0` for `x->1` 
```
1/4*x^2*(Pi-2*ArcSin(x))+1/4*(-1+x^2)*(x/Sqrt(1-x^2)-ArcTan(x/Sqrt(1-x^2))+(-x^2*ArcTan(x/Sqrt(1-x^2)))/(1-x^2))
```

**Comment by axkr** [comment]
This issue should be solved.
Please open new issue after 2.0.0 release if necessary.
