### ISSUE TITLE
NRoots(((x^4)-100)==0) , stuck and doesn't return

### ISSUE THREAD

**Issue by YoussefAgagg** [axkr/symja_android_library#337]
when trying to find roots for equations of power  higher than 2 and the roots are real numbers the method is stuck and doesn't return and the CPU status shows that the application doing heavy calculations  
an example that doesn't return :
x^3-100==0
x^4-100==0
x^4-16==0

**Comment by axkr** [comment]
Solved in https://github.com/Hipparchus-Math/hipparchus/issues/177 - 2.1-SNAPSHOT

**Comment by axkr** [comment]
The Hipparchus 2.1 version will be used in the next Symja release > 2.0.0.
Please open new issue if necessary.
