### ISSUE TITLE
ExpandAll(Surd(-3.0, 3))-(-3)^(1/3) give different result in symbolic and numeric mode

### ISSUE THREAD

**Issue by tranleduy2000** [axkr/symja_android_library#37]
```
ExpandAll(Surd(-3.0, 3))-(-3)^(1/3) 
```
When I calculate in symbolic format, it give correct result, but it give different result in numeric mode
![image](https://user-images.githubusercontent.com/19369448/38926429-d8a3bd94-432c-11e8-9637-0198f98f0e25.png)

**Comment by axkr** [comment]
As of wolfram alpha the first evaluation  is wrong:
[Surd[-3,3]-(-3)^(1/3)](http://www.wolframalpha.com/input/?i=Surd%5B-3,3%5D-(-3)%5E(1%2F3))

**Comment by tranleduy2000** [comment]
I think the result not wrong, but one result in real‐valued root and other in principal root

**Comment by tranleduy2000** [comment]
The result should be list, ``Sqrt(-4)=={I*2,-I*2}``
