### ISSUE TITLE
Create specific artifact for the script engine

### ISSUE THREAD

**Issue by rjolly** [axkr/symja_android_library#370]
matheclipse-io draws a lot of dependencies, would it be possible to create a separate artifact for the script engine, say matheclipse-script?

**Comment by axkr** [comment]
The separate `matheclipse-script` artifact is now created.

There is a minimal example for the Mathematica syntax:
- https://github.com/axkr/symja_android_library/blob/master/symja_android_library/matheclipse-script/src/test/java/org/matheclipse/script/examples/MathScriptEngineExample.java

Unfortunately it may require some additional "customizing". 
Especially, if you would like to use some `matheclipse-io`functions:
- https://github.com/axkr/symja_android_library/blob/194be4162d6fd71e657f1e38d5b55ad978a4d28c/symja_android_library/matheclipse-io/src/test/java/org/matheclipse/io/system/AbstractTestCase.java#L212

What are you're preferred default settings?

**Comment by axkr** [comment]
In the latest commit I defined a minimal setting and make `matheclips-io` functions available if the dependencies are on the classpath.

**Comment by rjolly** [comment]
I am not sure why you need to do anything to make `matheclipse-io` functions available.

I mean, the reflective call will happen sooner or later if the script contains related code, so what is the point to make this call in the engine constructor?

Otherwise, LGTM.

**Comment by axkr** [comment]
> I mean, the reflective call will happen sooner or later if the script contains related code, so what is the point to make this call in the engine constructor?

We don't use reflective calls for built-in functions (anymore). For using `matheclipse-io` functions we have to do an initialization once at startup.

**Comment by rjolly** [comment]
You mean, there is a script compilation phase? Even if so, why not wait until then, and then fail if the function is not on the classpath (as opposed to when the engine is instantiated)?

**Comment by axkr** [comment]
The separate matheclipse-script artifact is created. 
Can we close this issue and open a new issue if necessary after 2.0.0 release?

**Comment by rjolly** [comment]
Yes, no problem.
