### ISSUE TITLE
[Feature request] improve ExprPreprocessor code generator 

### ISSUE THREAD

**Issue by axkr** [axkr/symja_android_library#38]
There is already a tool [ExprPreprocessor](https://github.com/axkr/symja_android_library/blob/master/symja_android_library/tools/src/main/java/org/matheclipse/core/preprocessor/ExprPreprocessor.java) which converts Symja expressions in Java line comments opened by  `// [$ ... $] ` or  `//[$ ... $] ` and closed by `// $$` or `//$$` into Java source code.

In the example from the [TrigToExp ](https://github.com/axkr/symja_android_library/blob/master/symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/reflection/system/TrigToExp.java) function the Symja expression `2/(E^x-E^(-x))` 

```
 MATCHER.caseOf(Csch(x_), //
  		x -> // [$ 2/(E^x-E^(-x)) $]
 		F.Null); // $$);
```

will be converted into Java source code
```
 MATCHER.caseOf(Csch(x_), //
  		x -> // [$ 2/(E^x-E^(-x)) $]
 		F.Times(F.C2, F.Power(F.Plus(F.Negate(F.Power(F.E, F.Negate(x))), F.Power(F.E, x)), -1))); // $$);
```

The idea is to create a more powerful java codegen tool which can generate:
- Javadoc from markdown description of functions See the [MarkdownToHTML](https://github.com/axkr/symja_android_library/blob/master/symja_android_library/tools/src/main/java/org/matheclipse/core/preprocessor/MarkdownToHTML.java) tool
- math expressions for [java.lang.Math](https://docs.oracle.com/javase/8/docs/api/java/lang/Math.html) functions
- math expressions for java.math.BigInteger, java.math.BigDecimal add,multiply,pow,... functions
- math expressions for [org.hipparchus.fraction.BigFraction](https://github.com/Hipparchus-Math/hipparchus/blob/master/hipparchus-core/src/main/java/org/hipparchus/fraction/BigFraction.java)
- math expressions for [org.hipparchus.FieldElement](https://github.com/Hipparchus-Math/hipparchus/blob/master/hipparchus-core/src/main/java/org/hipparchus/FieldElement.java) or [org.apache.commons.math4.FieldElement](https://github.com/apache/commons-math/blob/master/src/main/java/org/apache/commons/math4/FieldElement.java)
- [HornerForm](https://github.com/axkr/symja_android_library/blob/master/symja_android_library/doc/functions/HornerForm.md), [MathMLForm](https://github.com/axkr/symja_android_library/blob/master/symja_android_library/doc/functions/MathMLForm.md), [TeXForm](https://github.com/axkr/symja_android_library/blob/master/symja_android_library/doc/functions/TeXForm.md)... See [OutputFunctions](https://github.com/axkr/symja_android_library/blob/master/symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/builtin/OutputFunctions.java)

The ExprPreprocessor tool could be merged with a tool like: [java_preprocessor](https://github.com/jpsember/java_preprocessor) to be a more general standalone tool for Java code generation.
 
At the moment the ExprPreprocessor tool is a console app. After the `▶ ` prompt, you can input the file path you would like to convert. 
In Eclipse you can right click on a Java file and select menu `Copy Qualified Name` and insert this file path into the console app and press the ENTER button.
The generated source will replace the current file.

```
Input qualified Java file for converting Symja expressions to Java source
▶ /symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/reflection/system/TrigToExp.java
```

See also the very simple [java_codegen project](https://github.com/axkr/java_codegen)

**Comment by tranleduy2000** [comment]
Does it affect multiple files?

**Comment by axkr** [comment]
No it‘s an enhancement Further Definition follows later
