### ISSUE TITLE
Implement convenience selection of principle solution

### ISSUE THREAD

**Issue by HannesWell** [axkr/symja_android_library#450]
**Is your feature request related to a problem? Please describe.**

When solving equations with multiple solutions like `Solve(E^x-2==0,x)` the solution is
`{{𝗑−>𝖢𝗈𝗇𝖽𝗂𝗍𝗂𝗈𝗇𝖺𝗅𝖤𝗑𝗉𝗋𝖾𝗌𝗌𝗂𝗈𝗇(𝖫𝗈𝗀(𝟤)+𝟤·ⅈ··𝖼𝟣,𝖼𝟣∈ℤ)}}`.

**Describe the solution you'd like**

It would be great to be able to select the principle solution in a simple way, in this case the solution for `c1=0` which leads to `x -> Log(2)`. Nevertheless in general it can be a desired feature to have' all' solutions as they are returned now, for example if one wants to have a solution in a certain interval.

**Describe alternatives you've considered**

An alternative would be to check for the `𝖢𝗈𝗇𝖽𝗂𝗍𝗂𝗈𝗇𝖺𝗅𝖤𝗑𝗉𝗋𝖾𝗌𝗌𝗂𝗈𝗇` when evaluating the solution. Then the variables can be found (in this case only c1) and the expression can be reevaluated with all variables set to zero.
This approach would also allow to handle an infinite number of solutions in more custom/specific ways (like one would actually get for `Solve(sin(x)==0.5,x)`).

**Comment by TiagoCavalcante** [comment]
Wolfram Cloud returns {{x−> Log(2)+2⋅ⅈ⋅π⋅c1 if c1∈Z)}}.

Maybe a solution to this is to add this formatting to 𝖢𝗈𝗇𝖽𝗂𝗍𝗂𝗈𝗇𝖺𝗅𝖤𝗑𝗉𝗋𝖾𝗌𝗌𝗂𝗈𝗇.

**Comment by HannesWell** [comment]
> Wolfram Cloud returns {{x−> Log(2)+2⋅ⅈ⋅π⋅c1 if c1∈Z)}}.
> 
> Maybe a solution to this is to add this formatting to 𝖢𝗈𝗇𝖽𝗂𝗍𝗂𝗈𝗇𝖺𝗅𝖤𝗑𝗉𝗋𝖾𝗌𝗌𝗂𝗈𝗇.

That's right and it's a correct result. Therefore my request is not to change the standard result.
However because there are cases where one just wants one solution respectively the most obvious one, which is sometimes called principle solution and would be in this case the solution with `c1=0`, it would be great if either one can set up Symja to take only the principle solution (for example the REDUCE CAS has a switch called `ALLBRANCH` and can be set to off to only take the principle branch: http://www.reduce-algebra.com/switches.php).

Or to have a dedicated command/environment that behaves accordingly, something `PrincipleBranch({{𝗑−>𝖢𝗈𝗇𝖽𝗂𝗍𝗂𝗈𝗇𝖺𝗅𝖤𝗑𝗉𝗋𝖾𝗌𝗌𝗂𝗈𝗇(𝖫𝗈𝗀(𝟤)+𝟤·ⅈ··𝖼𝟣,𝖼𝟣∈ℤ)}})` that then returns `{{x-> Log(2)}}`.
Instead of being applied on the rule set this could also be applied on each rule.
A third approach would be to wrap the Solve command with such an command or somehow make Solve configurable in this regard.
