### ISSUE TITLE
jbang enablement

### ISSUE THREAD

**Issue by maxandersen** [axkr/symja_android_library#515]
**Is your feature request related to a problem? Please describe.**

I saw https://axkr.github.io/blog/2022/JShellUsageWithSymja.html and it is a really nice usage of jshell.

I realized that with jbang it could be made even simpler. As things are today you can do:

```
jbang --deps org.matheclipse:matheclipse-core:2.0.0,org.matheclipse:matheclipse-io:2.0.0 -s https://github.com/axkr/symja_android_library/blob/master/symja_android_library/start-symja.jsh -i
```

And you get the same kind of jshell as the blog talks about but without having to download any library/script files on your own.

You can even do it without having any java installed by first running:

`curl -Ls https://sh.jbang.dev | bash -s - app setup; source ~/<shellprofile>`

But we can simplify that first commend, to just:

```
jbang -s https://github.com/axkr/symja_android_library/blob/master/symja_android_library/start-symja.jsh -i
```

if https://github.com/axkr/symja_android_library/blob/master/symja_android_library/start-symja.jsh would get this added:

```
//DEPS org.matheclipse:matheclipse-core:2.0.0,org.matheclipse:matheclipse-io:2.0.0 
```

That will be ignored by java/jshell but jbang will use it to pickup dependencies automatically.

We can go even futher and shorten it to:

```
jbang -s symjajsh@axkr -i
```

That could be done if you created a `axkr/jbang-catalog` repo with a jbang-catalog.json that points to the start-symja.jsh script (

I made example so `j! -s symjajsh@jbangdev/jbang-examples -i` works.

I'm happy to contribute such catalog if you create the repo. 

WDYT ?

**Comment by axkr** [comment]
@maxandersen  I created the `axkr/jbang-catalog` repo.
At the moment I must do some experiments with jbang to get the "complete picture".

There is probably also an option to let the apps working from jbang:
- https://github.com/axkr/symja_android_library/wiki/Installation

**Comment by maxandersen** [comment]
is there a maven GAV that has the console app ?

**Comment by axkr** [comment]
> is there a maven GAV that has the console app ?
Yes it's in the `matheclipse-io` artifact:
* https://github.com/axkr/symja_android_library/blob/07a9d34941bae3903ce56918da9cd697eb46c8d5/symja_android_library/matheclipse-io/pom.xml#L11

The apps are defined below this line:
* https://github.com/axkr/symja_android_library/blob/07a9d34941bae3903ce56918da9cd697eb46c8d5/symja_android_library/matheclipse-io/pom.xml#L124
