### ISSUE TITLE
Inconsistent variable name case (upper/lower) treatment

### ISSUE THREAD

**Issue by jsveiga** [axkr/symja_android_library#52]
### Is this a request for a feature or a bug report?

Bug report

### What is the current behavior?

(running current snapshot as of today)

It seems that symja considers single-letter variables names as case-sensitive, but multiple letter variables names are case-insensitive, so they get clobbered:

`

▶  a=0
In [1]: a=0
Out[1]: 0
▶  A=1
In [2]: A=1
Out[2]: 1
▶  a
In [3]: a
Out[3]: 0
▶  A
In [4]: A
Out[4]: 1
▶  foo=0
In [5]: foo=0
Out[5]: 0
▶  Foo=1
In [6]: Foo=1
Out[6]: 1
▶  foo
In [7]: foo
Out[7]: 1
▶  Foo
In [8]: Foo
Out[8]: 1
`

This can also be seen using "Variables()":

`

▶  Variables(b+B+bar+Bar)
In [10]: Variables(b+B+bar+Bar)
Out[10]: {b,B,bar}
`

### If this is a bug report, please provide steps to reproduce:

Start the symja console, and run the commands as above.

### What is the expected or desired behavior?  

Variable names with multiple letters should also be case sensitive.

### Please provide use cases for changing the current behavior:

General use, the inconsistent behaviour is unexpected for the user and may result in errors.

### Please describe your development environment (OS, browser, etc.):

Android (symja7), but this is upstream from symja8 (tested for symja8 on linux command line)

Thanks!

**Comment by axkr** [comment]
This is the expected behaviour.
If you would like to have a more Mathematica like parsing use 
`Config.PARSER_USE_LOWERCASE_SYMBOLS = false;`

Especially use the org.`matheclipse.core.eval.MMAConsole ` instead of `Console`

**Comment by jsveiga** [comment]
Thank you again! I'll try the config option.

best regards,

Joao
