### ISSUE TITLE
Simplify simple expression with old jar file 

### ISSUE THREAD

**Issue by sebospc** [axkr/symja_android_library#53]
### Is this a request for a feature or a bug report?

Bug report

### What is the current behavior?

 when i eval this expression : 
`0.0+-1.0(x-0.0)+1.0(x-0.0)(x-1.0)`
get
`plus((-1.0)*x,x*(-1.0+x))`
thats ok but when i use simplify it gives me
`plus[(-1.0)*x,x*(-1.0+x)]` 
and with the online demo it gives me:
![image](https://user-images.githubusercontent.com/20503334/41067437-3767786c-69ab-11e8-888f-a3018cb076d3.png)

### If this is a bug report, please provide steps to reproduce:
`IExpr result = util.evaluate("0.0+-1.0(x-0.0)+1.0(x-0.0)(x-1.0)");` (util is EvalEngine object) 
`IExpr simplified = engine.evaluate(F.Simplify(result));` 
### What is the expected or desired behavior?  

i want the expression simplified like the online demo.

### Please describe your development environment (OS, browser, etc.):

Using symja-2015-09-26.jar in **android**

### Other relevant information:

Probably this issue is fixed in the next jar files but i use this library in android because java 8 makes the android sdk up to 24 :(, so please don't recommend me change the version of library.
Thanks in advance.

**Comment by axkr** [comment]
The [NCalc](https://github.com/tranleduy2000/ncalc) and [Natural Calc](https://github.com/tranleduy2000/naturalcalc)  projects maintain a [Java 7 branch based on Retrolambda](https://github.com/tranleduy2000/symja_android_library).

Instead of `F.Simplify(result)` you can also try a `F.Expand(result)` or `F.ExpandAll(result)` to expand the expression.

**Comment by sebospc** [comment]
`System.out.println("Expanded : "+engine.evaluate(F.Expand(result)).toString());`
give:
`Expanded : expand[plus[times[-1.0,x],times[plus[-1.0,x],x]]]`
and
`System.out.println("Expanded All : "+engine.evaluate(F.ExpandAll(result)).toString());`
give:
`Expanded All : expandall[plus[times[-1.0,x],times[plus[-1.0,x],x]]]`
its look like he is not evaluating ,what am i doing wrong? :(

**Comment by sebospc** [comment]
StringBuilder uglyFunction = new StringBuilder("0.0+-1.0(x-0.0)+1.0(x-0.0)(x-1.0)");    
            EvalEngine util = new EvalEngine();
            IExpr result = util.evaluate(uglyFunction.toString());
            Config.PARSER_USE_LOWERCASE_SYMBOLS = false;
            EvalEngine engine = new EvalEngine(false);
            //simplify function
            IExpr outForLatex = engine.evaluate(F.Simplify(result));
            System.out.println("Expanded : "+engine.evaluate(F.Expand(result)););
            System.out.println("Expanded All : "+engine.evaluate(F.ExpandAll(result)).toString());
            //show the interpolation function 
            TeXUtilities texUtil = new TeXUtilities(engine, false);
            StringWriter stw = new StringWriter();
            texUtil.toTeX(outForLatex, stw);
            System.out.println("latex: " + stw.toString());

**Comment by tranleduy2000** [comment]
```java
String inputExpression = "0.0+-1.0(x-0.0)+1.0(x-0.0)(x-1.0)";
ExprEvaluator evaluator = new ExprEvaluator();
IExpr result = evaluator.eval(F.Simplify(evaluator.parse(inputExpression)));

//convert to TeX
TeXUtilities texEngine = new TeXUtilities(evaluator.getEvalEngine(), true);
final StringWriter output = new StringWriter();
texEngine.toTeX(result, output);

String texStr = output.toString();
```

**Comment by sebospc** [comment]
Thanks @tranleduy2000  and @axkr I found the problem 
when  **I dont use** this: `Config.PARSER_USE_LOWERCASE_SYMBOLS = false;`
The compiler gives me this error:
 `java.lang.ClassNotFoundException: Didn't find class "org.apache.log4j.Logger" `
so just add the log4j-1.2.17.jar to my libs and now works like the online demo, thanks a lot :).
Last output: `-2.0*x+x^2`
