### ISSUE TITLE
Solving Solve({{1,2},{1,4}}.{{x},{y}}=={{1},{-3}},{x,y})

### ISSUE THREAD

**Issue by tranleduy2000** [axkr/symja_android_library#535]
Could you please implement matrix solving for `Solve` function?

Example input:
```
Solve({{1,2},{1,4}}.{{x},{y}}=={{1},{-3}},{x,y})
```

Example result:

<img width="833" alt="image" src="https://user-images.githubusercontent.com/19369448/174142747-531836ed-fa15-41c7-8f40-f84968c69181.png">

**Comment by axkr** [comment]
At the moment this can be done with `LinearSolve`:

```
LinearSolve({{1,2},{1,4}}, {1, -3})
```

So the form of `Solve` must be converted to `LinearSolve` and the solution assigned back to the variables or we can create multiple "equations" from the matrix form and try to solve it with `Solve`.
