### ISSUE TITLE
CDF(NormalDistribution(),x) only returns numeric values for x <= 0

### ISSUE THREAD

**Issue by jsveiga** [axkr/symja_android_library#56]
# Submit a feature request or bug report

### Is this a request for a feature or a bug report?

bug report

### What is the current behavior?

CDF(NormalDistribution(),-0.41)

0.3409

CDF(NormalDistribution(),0.41)

0.5⋅Erfc(-0.28991)

When it should be 1 - 0.3409 = 0.6591

Same thing happens if CDF(NormalDistribution(m,s),x) is used (with mean and stddev values), for x>m.

(note: PDF and CDF are not documented on
https://github.com/axkr/symja_android_library/blob/master/symja_android_library/doc/index.md#reference-of-built-in-symbols
so I'm not sure if this is as designed)

### If this is a bug report, please provide steps to reproduce:

Issue the example commands on http://symjaweb.appspot.com/

### What is the expected or desired behavior?  

CDF(NormalDistribution(),0.41) should return 0.6591, CDF(NormalDistribution(m,s),x) with x > m should return valid values.

### Please provide use cases for changing the current behavior:

Statistics usage, where the CDF of the Bell distribution is needed or x > mean.

### Please describe your development environment (OS, browser, etc.):

I'm developing for android (android studio on linux), using the symja-java7 branch, but only tested this in http://symjaweb.appspot.com/ (I'm away from my development computer at the moment).

**Comment by axkr** [comment]
In commit 37f5ef9 I switched to `de.lab4inf.math.functions.Erf` `erf()` and `erfc()` method implementations.

The formerly used `org.hipparchus.special.Erf` method are more constrained in argument value range.

**Comment by axkr** [comment]
Related to #4 Port statistics functions from tensor project

**Comment by jsveiga** [comment]
Thank you!
