### ISSUE TITLE
FindRoot methods "Newton" and "Bisection" return xMax if there is no root in the interval

### ISSUE THREAD

**Issue by jsveiga** [axkr/symja_android_library#60]
### Is this a request for a feature or a bug report?

Bug

### What is the current behavior?

If no root is found in the interval, FindRoot returns the interval max value, when using Newton or Bisection methods.

### If this is a bug report, please provide steps to reproduce:

Evaluate [FindRoot ](https://github.com/axkr/symja_android_library/blob/master/symja_android_library/doc/functions/FindRoot.md)for a function with no root using Newton or Bisection:

FindRoot(cos(x) + 2, {x, 0, 5}, Method->bisection)
{x->5.0}

FindRoot(cos(x) + 2, {x, 0, 5}, Method->newton)
{x->5.0}

### What is the expected or desired behavior?  

Should not return a root, like for the other methods:

FindRoot(cos(x) + 2, {x, 0, 5}, method->brent)
Error: FindRoot: interval does not bracket a root: ...
{}

FindRoot(cos(x) + 2, {x, 0, 5}, method->muller)
Error: FindRoot: interval does not bracket a root: ...
{}

### Please provide use cases for changing the current behavior:

Any usage of FindRoot with Bisection or Newton, when there is no solution in the interval.

### Please describe your development environment (OS, browser, etc.):

Linux, Android Studio (but these test were ran at http://symjaweb.appspot.com/)

Thanks!

**Comment by axkr** [comment]
Bisection solver will be used if the Newton solver fails.
So this is probably only a problem with the bisection solver.

**Comment by axkr** [comment]
Implemented a workaround with 4069b5b.
Can be removed if hipparchus 1.4 is available
