### ISSUE TITLE
JAS libs version 2.65851 commit broke compiling with matheclipse-core-1.0.0-SNAPSHOT-jar-with-dependencies.jar in Android Studio

### ISSUE THREAD

**Issue by jsveiga** [axkr/symja_android_library#63]
### Is this a request for a feature or a bug report?

Bug (not sure, maybe I'm doing something wrong)

### What is the current behavior?

After the commits:

Use latest JAS version 2.6.5851 from Maven
Use JAS libs version 2.6.5851 
bc68d4464582f71cf41fbc4d9735939a69b4fc62
78423454ee2eb765a2ce4cea75e93107d19f7065

Compiling an app using 

matheclipse-core-1.0.0-SNAPSHOT-jar-with-dependencies.jar

results in:

`Annotation processors must be explicitly declared now.  The following dependencies on the compile classpath are found to contain annotation processor.  Please add them to the annotationProcessor configuration.`
`matheclipse-core-1.0.0-SNAPSHOT-jar-with-dependencies.jar (project :matheclipse-core)`
`Alternatively, set android.defaultConfig.javaCompileOptions.annotationProcessorOptions.includeCompileClasspath = true to continue with previous behavior.  Note that this option is deprecated and will be removed in the future.
See https://developer.android.com/r/tools/annotation-processor-error-message.html for more details.
`

I have tried both setting android.defaultConfig.javaCompileOptions.annotationProcessorOptions.includeCompileClasspath = true
and also configuring the matheclipse-core dependency as "annotationProcessor" and "implementation" (compile) as the linked documentation suggests. The app then compiles without error, but matheclipse-core does not work (evaluate returns the input string as is).

Reverting these two commits fixes compilation and library works (as of "Integrate gives wrong result" commit, fe4916e6110a4f28ee9db0a56ee21fbd53651ce9).

### If this is a bug report, please provide steps to reproduce:

Use matheclipse-core-1.0.0-SNAPSHOT-jar-with-dependencies.jar as a dependency in an Android Studio 3.1.3 project, and compile.

### What is the expected or desired behavior?  

Clear compilation of app with matheclipse-core-1.0.0-SNAPSHOT-jar-with-dependencies.jar

### Please describe your development environment (OS, browser, etc.):

Android Studio 3.1.3, Linux Kubuntu and Windows 10

**Comment by jsveiga** [comment]
I'm investigating this and it seems the compilation problem is triggered by log4j-core-2.5.jar that was added with the JAS libs version 2.65851 commit.

The link in the error message (https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration#annotationProcessor_config) says "The plugin assumes a dependency is an annotation processor if its JAR file contains the following file: META-INF/services/javax.annotation.processing.Processor."

and indeed the log4j-core-2.5.jar has that file.

The matheclipse-core-1.0.0-SNAPSHOT-jar-with-dependencies.jar from before the JAS 2.65851 commit doesn't have that in the META-INF, but after it it does.

That should only mean it provides annotation processor services, and adding the annotationProcessor dependency in gradle for it should solve the problem, but although that makes the compilation work, the app no longer works, so it's something else.

At first I thought evaluate() was returning the same string, but it's actually freezing.

I tracked it down with the debugger, and it is stopping at:

    (F.class)

    public static final void await() throws InterruptionException {

        COUNT_DOWN_LATCH.await();

    }

If you need any further testing, please let me know.

**Comment by axkr** [comment]
This means, that `COUNT_DOWN_LATCH.countDown()` wasn't called in the initialization of F.class.

Can you try adding `F.initSymbols()` after setting the Config flags?

If that doesn't work xan you try setting `Config.JAS_NO_THREADS = false;`

**Comment by jsveiga** [comment]
Hi, neither worked, but I follow them and found that when the F.class static initializer runs, when it gets to

ComputerThreads.NO_THREADS = Config.JAS_NO_THREADS;

this causes an exception and aborts the try, including the runnable that would do the F.COUNT_DOWN_LATCH.countDown(); - so you are right, it is not called when F.class is initialized.

Note that the app does not freeze at this point; there's only a logcat output from the catch. The app will only freezes when evaluate() is called with an operation later on.

The logcat shows:

07-14 03:02:29.792 17630-17630/br.eng.it.jsvcalc W/System.err: java.lang.ExceptionInInitializerError
07-14 03:02:29.793 17630-17630/br.eng.it.jsvcalc W/System.err:     at org.matheclipse.core.expression.F.<clinit>(F.java:3312)
        at org.matheclipse.core.eval.EvalEngine.<init>(EvalEngine.java:192)
        at org.matheclipse.core.eval.EvalEngine.<init>(EvalEngine.java:308)
        at org.matheclipse.core.eval.EvalEngine$1.initialValue(EvalEngine.java:72)
07-14 03:02:29.794 17630-17630/br.eng.it.jsvcalc W/System.err:     at org.matheclipse.core.eval.EvalEngine$1.initialValue(EvalEngine.java:64)
        at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:180)
        at java.lang.ThreadLocal.get(ThreadLocal.java:170)
        at org.matheclipse.core.eval.EvalEngine.get(EvalEngine.java:82)
        at br.eng.it.jsvcalc.StackItem.<clinit>(StackItem.java:24)
07-14 03:02:29.795 17630-17630/br.eng.it.jsvcalc W/System.err:     at br.eng.it.jsvcalc.StackItem.setPrefs(StackItem.java:219)
        at br.eng.it.jsvcalc.MainActivity.onCreate(MainActivity.java:124)
        at android.app.Activity.performCreate(Activity.java:6984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1235)
07-14 03:02:29.796 17630-17630/br.eng.it.jsvcalc W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2783)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2909)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1606)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
07-14 03:02:29.797 17630-17630/br.eng.it.jsvcalc W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6592)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)
07-14 03:02:29.799 17630-17630/br.eng.it.jsvcalc W/System.err: Caused by: java.lang.NullPointerException: Attempt to get length of null array
        at org.apache.logging.log4j.util.ReflectionUtil$PrivateSecurityManager.getCallerClass(ReflectionUtil.java:308)
        at org.apache.logging.log4j.util.ReflectionUtil.getCallerClass(ReflectionUtil.java:218)
07-14 03:02:29.800 17630-17630/br.eng.it.jsvcalc W/System.err:     at org.apache.logging.log4j.util.ReflectionUtil.getCallerClass(ReflectionUtil.java:197)
        at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:72)
        at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:57)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:140)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:41)
07-14 03:02:29.801 17630-17630/br.eng.it.jsvcalc W/System.err:     at org.apache.logging.log4j.LogManager.getContext(LogManager.java:267)
        at org.apache.log4j.Logger$PrivateManager.getContext(Logger.java:59)
        at org.apache.log4j.Logger.getLogger(Logger.java:41)
        at edu.jas.kern.ComputerThreads.<clinit>(ComputerThreads.java:30)


With the older version that works, this exception does not occur.

**Comment by axkr** [comment]
Ok, so we can track down the exception to:

```
07-14 03:02:29.799 17630-17630/br.eng.it.jsvcalc W/System.err: Caused by: java.lang.NullPointerException: Attempt to get length of null array
at org.apache.logging.log4j.util.ReflectionUtil$PrivateSecurityManager.getCallerClass(ReflectionUtil.java:308)
at org.apache.logging.log4j.util.ReflectionUtil.getCallerClass(ReflectionUtil.java:218)
07-14 03:02:29.800 17630-17630/br.eng.it.jsvcalc W/System.err: at org.apache.logging.log4j.util.ReflectionUtil.getCallerClass(ReflectionUtil.java:197)
at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:72)
at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:57)
at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:140)
at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:41)
07-14 03:02:29.801 17630-17630/br.eng.it.jsvcalc W/System.err: at org.apache.logging.log4j.LogManager.getContext(LogManager.java:267)
at org.apache.log4j.Logger$PrivateManager.getContext(Logger.java:59)
at org.apache.log4j.Logger.getLogger(Logger.java:41)
at edu.jas.kern.ComputerThreads.(ComputerThreads.java:30)
```

**Comment by axkr** [comment]
See comment from JAS issue:

>  Since Apache log4j was not working on Android there is the adapter package droidlog.jar which delegates the logging calls to native Android logging.
> In case you can not use droidlog.jar and not Apache log4j for some reason, there is an adapter package mylog.jar which delegates the logging calls to native Java logging.
>If these adapters do not work, please, reopen the issue.

**Comment by axkr** [comment]
According to this issue:
https://issues.apache.org/jira/browse/LOG4J2-2220

the problem doesn't seem to be solved. I think I will revert back to JAS version 2.6.5803

**Comment by tranleduy2000** [comment]
``log4j`` not compatible with Android OS, please use log ``slf4j-android`` and ``log4j-over-slf4j``

**Comment by axkr** [comment]
Could you please try the changes in b62f689

**Comment by jsveiga** [comment]
Sorry, still the same.

When it gets to ComputerThreads.NO_THREADS = Config.JAS_NO_THREADS; it aborts to the printStackTrace() and logcat shows:

07-13 18:04:43.483 22228-22228/br.eng.it.jsvcalc W/System.err: java.lang.ExceptionInInitializerError
07-13 18:04:43.484 22228-22228/br.eng.it.jsvcalc W/System.err:     at org.matheclipse.core.expression.F.<clinit>(F.java:3310)
07-13 18:04:43.485 22228-22228/br.eng.it.jsvcalc W/System.err:     at org.matheclipse.core.form.tex.TeXFormFactory.init(TeXFormFactory.java:1503)
07-13 18:04:43.486 22228-22228/br.eng.it.jsvcalc W/System.err:     at org.matheclipse.core.form.tex.TeXFormFactory.<init>(TeXFormFactory.java:1006)
07-13 18:04:43.488 22228-22228/br.eng.it.jsvcalc W/System.err:     at org.matheclipse.core.form.tex.TeXFormFactory.<init>(TeXFormFactory.java:997)
        at org.matheclipse.core.eval.TeXUtilities.<init>(TeXUtilities.java:32)
07-13 18:04:43.489 22228-22228/br.eng.it.jsvcalc W/System.err:     at br.eng.it.jsvcalc.StackItem.<clinit>(StackItem.java:24)
07-13 18:04:43.490 22228-22228/br.eng.it.jsvcalc W/System.err:     at br.eng.it.jsvcalc.StackItem.setPrefs(StackItem.java:219)
07-13 18:04:43.491 22228-22228/br.eng.it.jsvcalc W/System.err:     at br.eng.it.jsvcalc.MainActivity.onCreate(MainActivity.java:124)
07-13 18:04:43.492 22228-22228/br.eng.it.jsvcalc W/System.err:     at android.app.Activity.performCreate(Activity.java:6975)
07-13 18:04:43.493 22228-22228/br.eng.it.jsvcalc W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
07-13 18:04:43.494 22228-22228/br.eng.it.jsvcalc W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
07-13 18:04:43.495 22228-22228/br.eng.it.jsvcalc W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
07-13 18:04:43.496 22228-22228/br.eng.it.jsvcalc W/System.err:     at android.app.ActivityThread.-wrap11(Unknown Source:0)
07-13 18:04:43.499 22228-22228/br.eng.it.jsvcalc W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
07-13 18:04:43.500 22228-22228/br.eng.it.jsvcalc W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:105)
07-13 18:04:43.501 22228-22228/br.eng.it.jsvcalc W/System.err:     at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
07-13 18:04:43.502 22228-22228/br.eng.it.jsvcalc W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
07-13 18:04:43.503 22228-22228/br.eng.it.jsvcalc W/System.err:     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
07-13 18:04:43.504 22228-22228/br.eng.it.jsvcalc W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
07-13 18:04:43.507 22228-22228/br.eng.it.jsvcalc W/System.err: Caused by: java.lang.NullPointerException: Attempt to get length of null array
07-13 18:04:43.508 22228-22228/br.eng.it.jsvcalc W/System.err:     at org.apache.logging.log4j.util.ReflectionUtil$PrivateSecurityManager.getCallerClass(ReflectionUtil.java:308)
07-13 18:04:43.509 22228-22228/br.eng.it.jsvcalc W/System.err:     at org.apache.logging.log4j.util.ReflectionUtil.getCallerClass(ReflectionUtil.java:218)
07-13 18:04:43.510 22228-22228/br.eng.it.jsvcalc W/System.err:     at org.apache.logging.log4j.util.ReflectionUtil.getCallerClass(ReflectionUtil.java:197)
07-13 18:04:43.511 22228-22228/br.eng.it.jsvcalc W/System.err:     at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:72)
07-13 18:04:43.513 22228-22228/br.eng.it.jsvcalc W/System.err:     at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:57)
07-13 18:04:43.514 22228-22228/br.eng.it.jsvcalc W/System.err:     at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:140)
07-13 18:04:43.515 22228-22228/br.eng.it.jsvcalc W/System.err:     at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:41)
07-13 18:04:43.517 22228-22228/br.eng.it.jsvcalc W/System.err:     at org.apache.logging.log4j.LogManager.getContext(LogManager.java:267)
07-13 18:04:43.518 22228-22228/br.eng.it.jsvcalc W/System.err:     at org.apache.log4j.Logger$PrivateManager.getContext(Logger.java:59)
        at org.apache.log4j.Logger.getLogger(Logger.java:41)
07-13 18:04:43.519 22228-22228/br.eng.it.jsvcalc W/System.err:     at edu.jas.kern.ComputerThreads.<clinit>(ComputerThreads.java:30)
07-13 18:04:43.520 22228-22228/br.eng.it.jsvcalc W/System.err: 	... 20 more

**Comment by tranleduy2000** [comment]
Could you upload your grade files?

**Comment by jsveiga** [comment]
Sure!

Note: on the app/build.gradle I have both your java7 lib and Axel's java8 lib (I switch between them here and on settings.gradle, also changing the minSdkVersion). The java8 lib with the latest JAS requires the "annotationProcessor" dependency.

I also added your email (I don't have Axel's) on the bitbucket repository, so I think you can see it all there if you want. https://bitbucket.org/jsveiga/jsvcalc/src/master/ 

If you want to compile&run, you'll need to either edit settings.gradle and build.gradle to use your java7 lib, or revert to the "complex tex symja8 update" commit (it has Axel's lib but with reverted JAS update). The current one is the one with the above error.

thanks for your help!

[gradle.zip](https://github.com/axkr/symja_android_library/files/2202974/gradle.zip)

**Comment by axkr** [comment]
My account is axelclk on bitbucket

**Comment by jsveiga** [comment]
Thank you, I've added you too.

**Comment by tranleduy2000** [comment]
I fixed this problem by add 
```gradle
        javaCompileOptions {
            annotationProcessorOptions {
                includeCompileClasspath false
            }
        }
```

Note that java 8 not support instant run, you need disable instant run before build.
![image](https://user-images.githubusercontent.com/19369448/42873022-82a36f02-8aa8-11e8-9651-d2d52390716b.png)

**Comment by tranleduy2000** [comment]
Should close this issue?

**Comment by jsveiga** [comment]
Yes, sorry, closing now.
