### ISSUE TITLE
Incorrect/Strange TeXUtilities.toTeX output

### ISSUE THREAD

**Issue by jsveiga** [axkr/symja_android_library#64]
### Is this a request for a feature or a bug report?

Bug

### What is the current behavior?

        TeXUtilities t = new TeXUtilities(EvalEngine.get(), EvalEngine.get().isRelaxedSyntax());
        StringWriter a = new StringWriter();
        t.toTeX("3-I*2", a);
        Log.d(TAG,  "1) " + a.toString());
        // ok
        // prints: 1) 3-2\,i
        //
        a = new StringWriter();
        t.toTeX("4-I*5", a);
        Log.d(TAG,  "2) " + a.toString());
        // ok
        // prints: 2) 4-5\,i
        //
        a = new StringWriter();
        t.toTeX("3.0-I*2.0", a);
        Log.d(TAG,  "3) " + a.toString());
        // not ok
        // prints: 3) 3.0-0.0 + 2.0\,i
        //
        a = new StringWriter();
        t.toTeX("3-I*2", a);
        Log.d(TAG,  "4) " + a.toString());
        // now it seems to stay "broken" even for the same input that worked before
        // prints: 4) 0.0 + -2.0\,i +3
        //
        t = new TeXUtilities(EvalEngine.get(), EvalEngine.get().isRelaxedSyntax());
        a = new StringWriter();
        t.toTeX("4-I*5", a);
        Log.d(TAG,  "5) " + a.toString());
        // even after instantiating a new TexUtilities
        // prints: 5) 0.0 + -5.0\,i +4

Also (maybe related?), not wrong, but inconsistent:
"-i" results in "-1\\,i" 
whereas
"i*(-1.0)" results in "- i"

### If this is a bug report, please provide steps to reproduce:

Run the code above (I'm using Android Studio 3.1.3).

Note: I have this set:
        Config.EXPLICIT_TIMES_OPERATOR = true;
        Config.DOUBLE_EPSILON = 1e-300;
        Config.DOUBLE_TOLERANCE = Config.DOUBLE_EPSILON * 10.0D;

and I'm running the current snapshot (fe4916e6110a4f28ee9db0a56ee21fbd53651ce9), but with reverted jas 2.6.5851 commits : so I still have jas 2.6.5803 (java-algebra-system) and not 2.6.5851 (de.uni-mannheim.rz.krum)

### What is the expected or desired behavior?  

toTeX should return correct TeX for N.N-I*M.M, and a previous conversion should not change the result of the next one.

### Please describe your development environment (OS, browser, etc.):

Android Studio 3.1.2, Linux Kubuntu

**Comment by axkr** [comment]
Please test my last commit with your environment. I've not tested all possible `Config ` flags.

**Comment by jsveiga** [comment]
Thank you again,

It solved the a+b*I cases, and the "remembering" issue.

But I see that on testTeX015 you do expect -I and -I*(1.0) to result in -1\,i and \left( -1\,i \right), shown as -1i and (-1i). Shouldn't it be just -i ?

Also, the result depends on the order of the operands in the input; I'm not sure if that's intended. In my case the input to toTeX() is always an output of evaluate(), so the sequence is always the same, but the results are then correct but inconsistent:

(I'm going to type only what the rendered TeX looks like below, not the TeX source for clarity)

What we have now (default config flags):
-I => -1i
-I*1 => (-1i)
-1*I or I*(-1) => -i
(all these get out of evaluate() as -I, so I always get -1i)
IMO, they should all be -i

-I*1.0 => (-1i)
-1.0*I or I*(-1.0) => -i
(all these get out of evaluate() as I*(-1.0), so I always get -i)
IMO, they should all be -i, or -1.0 . i 

-I*2 => 2 . (-1i)
-2*I or I*(-2) => (-2) . i
IMO these should be -2 . i

-I*2.0 => 2.0 . (-1i)
-2.0*I or I*(-2.0) => (-2.0) . i
IMO these should be -2.0 . i

Thank you!

Joao

**Comment by axkr** [comment]
Added f78d065.

**Comment by jsveiga** [comment]
Worked beautifully! Thank you again!

Joao
