### ISSUE TITLE
Parser give wrong value, older version not have this bug.

### ISSUE THREAD

**Issue by tranleduy2000** [axkr/symja_android_library#66]
![image](https://user-images.githubusercontent.com/19369448/43186247-5262efb4-9018-11e8-8ba2-d7adae4e1381.png)

**Comment by axkr** [comment]
Is this a problem with the precision specified for numerical values?

See cac97627

**Comment by tranleduy2000** [comment]
Java can not parse number higher 64 bits, I think you should use ``BigDecimal`` instead of ``NumStr`` to keep exactly result

**Comment by tranleduy2000** [comment]
Thanks for your suggestion.
