### ISSUE TITLE
[BUG] 1/Sqrt(((Rationalize(0.000000000008854187817))*(Rationalize(0.00000125663706)))) returns wrong result

### ISSUE THREAD

**Issue by tranleduy2000** [axkr/symja_android_library#698]
There is a test case:

```java
  public void testZZZ2() {
    String expr = "1/Sqrt(((Rationalize(0.000000000008854187817))*(Rationalize(0.00000125663706))))";
    ExprEvaluator evaluator = new ExprEvaluator();
    IExpr result = evaluator.eval(expr);
    assertEquals(result.toString(), "2.9979245819103837E8");
  }
```

<img width="714" alt="image" src="https://user-images.githubusercontent.com/19369448/225083138-a96f8c36-b8a7-464a-86d3-dcb5c65a8894.png">

**Comment by axkr** [comment]
Same as #697 

```java
  public void testZZZ2() {
    String expr = "1/Sqrt(((Rationalize(0.000000000008854187817,0 ))*(Rationalize(0.00000125663706,0)))) // N";
    ExprEvaluator evaluator = new ExprEvaluator();
    IExpr result = evaluator.eval(expr);
    assertEquals(result.toString(), "2.9979245819103837E8");
  }
```

**Comment by tranleduy2000** [comment]
Thanks, it works, but there is a problem:

`Rationalize[0.000000000008854187817]` returns the zero fraction which cannot convert back to decimal value.

There is wolframcloud result:
<img width="370" alt="image" src="https://user-images.githubusercontent.com/19369448/225246688-3cc171af-9ad0-431c-bc1f-8e0ebc776a63.png">

I think it should returns the decimal value instead of 0
