### ISSUE TITLE
[TeXParser] Add support for `\large 6666`

### ISSUE THREAD

**Issue by tranleduy2000** [axkr/symja_android_library#712]
The current text parser cannot parse the tex `\large 6666`.
Can you ignore this command in `TeXParser`?

**Comment by tranleduy2000** [comment]
Input: `\log_{22}5`
Expected result: `Log(5, 22)`


Current result: `5*Subscript(Log,22)`

**Comment by axkr** [comment]
The idea is to bubble up the subscript notation as `Log(n, #1)` in call stack and replace the slot if we detect the `Times` expression with the second argument.
Note : the base will be returned as first parameter: `Log(22,5)`

https://github.com/axkr/symja_android_library/blob/master/symja_android_library/doc/functions/Log.md

**Comment by axkr** [comment]
In [3a7d1f6](https://github.com/axkr/symja_android_library/commit/3a7d1f65853d2235a090351e9afafacbff1464c3) we try to ignore environmental setting errors.
Please test with more examples, if this works for you?

**Comment by tranleduy2000** [comment]
Hi, there is a tex which TexParser cannot parse:
```
\operatorname { lim } _ { n \rightarrow 0 } \frac { ( - 3 ) ^ { n } + 2.5 ^ { n } } { 1 - 5 ^ { n } }
```

<img width="345" alt="image" src="https://user-images.githubusercontent.com/19369448/229334378-a8a76562-ad8c-4331-a5e4-443453609c1d.png">

**Comment by tranleduy2000** [comment]
```
g \left(\right. x \left.\right) = ln \left(\right. \left|\right. x + 1 \left|\right. \left.\right)
```

<img width="225" alt="image" src="https://user-images.githubusercontent.com/19369448/229334458-535b152e-ac35-481b-87e3-8d822b2f57cf.png">


Should we add an option to config `f(x), g(x), h(x)` treated as a function instead of `f*x, g*x, h*x`?

https://en.wikipedia.org/wiki/Variable_(mathematics)#:~:text=Conventional%20variable%20names%5Bedit%5D

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/19369448/229334517-a634597f-4a48-4daf-9259-5b39d106bcc2.png">

**Comment by tranleduy2000** [comment]
```
\sqrt[3]{\sin x}
```
<img width="167" alt="image" src="https://user-images.githubusercontent.com/19369448/229335064-a85a656f-5dbf-4c32-93be-2ca734d73466.png">

**Comment by tranleduy2000** [comment]
The expression `\log x` should translate to `Log10(x)` (base 10) instead of `Log(x)` (base e)

**Comment by tranleduy2000** [comment]
These expression should translate with head `List` or `Sequence`:

```
\left\{ \begin{array} { l } { y - x = 1814 } \\ { y = 9 x + 182 } \end{array} \right.

=> {{y-x==1814},{y==(9*x)+182}}

```

<img width="200" alt="image" src="https://user-images.githubusercontent.com/19369448/229335462-eb77f17d-1285-4250-b73b-92b8331e4393.png">


```
\left\{ \begin{array} { l } { 5 x + 2 y = 9 } \\ { x - 14 y = 5 } \end{array} \right.
```
<img width="194" alt="image" src="https://user-images.githubusercontent.com/19369448/229335722-180ec23c-1dca-4346-8506-de942818c764.png">

**Comment by tranleduy2000** [comment]
```
f \left(\right. x \left.\right) = - 7 \left(\left(\right. x - 2 \left.\right)\right)^{2} - 9
```

<img width="266" alt="image" src="https://user-images.githubusercontent.com/19369448/229336031-fc7aa30b-5a3e-4c4d-ba09-671a1690adb5.png">

**Comment by tranleduy2000** [comment]
```
\int (x^2 - y)dx
```
<img width="186" alt="image" src="https://user-images.githubusercontent.com/19369448/229336578-e9cc89be-1196-47dd-bfc3-40588fed1020.png">

**Comment by tranleduy2000** [comment]
The tex `\sin a \cos b` should translate to `Sin(a)*Cos(b)` instead of `Sin(a * Cos(b))`

**Comment by tranleduy2000** [comment]
The tex `\sin(\cos \theta)` should translate to `Sin(Cos(θ))` instead of `Sin(cosθ)`
<img width="121" alt="image" src="https://user-images.githubusercontent.com/19369448/229336729-1b31c020-c4a4-481f-86ef-4bfb89597bc8.png">

**Comment by tranleduy2000** [comment]
> The idea is to bubble up the subscript notation as `Log(n, #1)` in the call stack and replace the slot if we detect the `Times` expression with the second argument.
> 
> Note : the base will be returned as first parameter: `Log(22,5)`
> 
> * https://github.com/axkr/symja_android_library/blob/master/symja_android_library/doc/functions/Log.md
> 
> Which other cases can be implemented like this?

Another special case: `\log_2345+3` should translate `Log(345, 2)+3` instead of `3+Log(2345,#1)`
<img width="160" alt="image" src="https://user-images.githubusercontent.com/19369448/229347791-1b0c1eeb-c327-49b6-b260-893c473fa6a5.png">

**Comment by axkr** [comment]
> The command `operatorname` with more than one argument cannot parse:
> 
> ```
> \operatorname{GCD}(3,5)
> ```
> 
> <img alt="image" width="153" src="https://user-images.githubusercontent.com/19369448/229755288-395738ee-ab3c-4cbc-ad40-f471a37e935d.png">

`gcd` in lower cases is predefined and works as expected. Should `GCD`give a new user defined symbol as header?

**Comment by tranleduy2000** [comment]
> > The command `operatorname` with more than one argument cannot parse:
> > ```
> > \operatorname{GCD}(3,5)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > <img alt="image" width="153" src="https://user-images.githubusercontent.com/19369448/229755288-395738ee-ab3c-4cbc-ad40-f471a37e935d.png">
> 
> `gcd` in lower cases is predefined and works as expected. Should `GCD`give a new user defined symbol as header?

I think the `\operatorname{Head}(arg1, arg2, ...)` command should be translated to `F.Function(Head, arg1, arg2, ...)` instead of depends on predefined latex commands. It will help the integration process more flexible.

**Comment by axkr** [comment]
> I think the `\operatorname{Head}(arg1, arg2, ...)` command should be translated to `F.Function(Head, arg1, arg2, ...)` instead of depends on predefined latex commands. It will help the integration process more flexible.

OK, the last commit tries to create a new `MathFunctionInterpretation` for every new `operatorname`

**Comment by tranleduy2000** [comment]
The expression parsed by TeXSliceParser is unable to calculate:
```

    public void testRec01() {
        ExprEvaluator evaluator = new ExprEvaluator();
        evaluator.eval("Pol[x, y] := FromPolarCoordinates[{x, y}]");

        TeXSliceParser teXSliceParser = new TeXSliceParser();
        IExpr input = teXSliceParser.parse("\\operatorname{Pol}(3,5)");

        IExpr result = evaluator.eval(F.N(input));
        assertEquals(result.toString(), "{5.83, 1.03}");
    }
```

```
expected:<[pol(3.0,5.0)]> but was:<[{5.83, 1.03}]>
Expected :pol(3.0,5.0)
Actual   :{5.83, 1.03}
```

**Comment by tranleduy2000** [comment]
```
\operatorname { det } \left| \begin{array} { l l } { 4 } & { 5
 } \\ { 7 } & { 2 } \end{array} \right|
```
<img width="145" alt="image" src="https://user-images.githubusercontent.com/19369448/230320681-bde0a4c8-0325-45ab-ada9-0bb63182bdd9.png">



```
\int \frac { 2 x - 1 } { x ^ { 2 } - 6 x + 9 } d x = a 
\operatorname { ln } ( x - 3 ) + \frac { b } { x - 3 } + C
```
<img width="519" alt="image" src="https://user-images.githubusercontent.com/19369448/230320659-67ef7faf-5541-4098-9e6c-fea1e2c6f858.png">


```
2 \operatorname { cos } ^ { 2 } x - \operatorname { cos } x - 1 = 0
```
<img width="239" alt="image" src="https://user-images.githubusercontent.com/19369448/230320787-586cd635-56e7-4752-bb2d-dba24440d393.png">


```
\{ \frac { \partial ( x ^ { 2 } y ^ { 4 } ) } { \partial x } , \frac { \partial ( x ^ { 2 } y ^ { 4 } ) } { \partial y } \}
```
<img width="228" alt="image" src="https://user-images.githubusercontent.com/19369448/230320948-1cb89ce8-550c-4e48-96d5-847db6389e7b.png">


```
y = x ^ { 3 } - 5 x + 1 , y ^ { \prime } = 3 x ^ { 2 } - 5
```
<img width="304" alt="image" src="https://user-images.githubusercontent.com/19369448/230321027-96c0d677-2a94-4553-b6f5-433657453c29.png">

```
\int \frac { 2 x - 1 } { x ^ { 2 } - 6 x + 9 } d x = a 
\operatorname { ln } | x - 3 | + \frac { b } { x - 3 } + C
```
<img width="427" alt="image" src="https://user-images.githubusercontent.com/19369448/230321143-67f3e663-5c01-45d9-b6ef-f87c8a54d67a.png">

```
\int _ { 0 } ^ { m } ( 2 x + 5 ) \cdot d x = 6
```
<img width="222" alt="image" src="https://user-images.githubusercontent.com/19369448/230321248-a76350ba-c54c-4454-846d-9f61723005cc.png">


```
\left. \begin{array} { l } { \frac { a ^ { \frac { 4 } { 3 } } ( a ^ { - \frac { 1 } { 3 } } + a ^ { \frac { 2 } { 3 } } ) } { a ^ { \frac { 1 } { 4
 } } ( a ^ { \frac { 3 } { 4 } } + a ^ { - \frac { 1 } { 4 } } ) } } \\
 { \frac { a ^ { \frac { 1 } { 3 } } \sqrt { b } + b ^ { - \frac { 1 } 
{ 4 } } } { \sqrt [ 6 ] { a } + \sqrt [ 6 ] { b } } } \\ { ( \sqrt [ 3
 ] { a } + \sqrt [ 3 ] { b } ) ( a ^ { \frac { 2 } { 3 } } + b ^ { \frac
 { 2 } { 3 } } - \sqrt [ 3 ] { a b } ) } \\ { ( a ^ { \frac { 1 } { 3 }
 } + b ^ { \frac { 1 } { 3 } } ) : ( 2 + \sqrt [ 3 ] { \frac { a } { b }
 } + \sqrt [ 3 ] { \frac { b } { a } } ) } \end{array} \right.
```
<img width="307" alt="image" src="https://user-images.githubusercontent.com/19369448/230321610-fe0d8520-09ea-4c50-9bb0-647df2611522.png">


```
\left. 
\begin{array} { l }
 { \int _ { 0 } ^ { 1 } ( y ^ { 3 } + 3 y ^ { 2 } - 2 ) d y } \\ 
{ \int _ { 4 } ^ { 4 } ( t + \frac { 1 } { \sqrt { t } } - \frac { 1 } { t ^ { 2 } } ) d t }
 \end{array}
 \right.
```
<img width="208" alt="image" src="https://user-images.githubusercontent.com/19369448/230321677-59b60944-6c32-4b5e-a2f0-ed3958377f04.png">

```
( \sqrt { x } ) ^ { \prime }
```
<img width="97" alt="image" src="https://user-images.githubusercontent.com/19369448/230321767-bdfa6ece-23a3-445a-98aa-749921604458.png">


```
\frac{d f(x)}{dx}
```
<img width="136" alt="image" src="https://user-images.githubusercontent.com/19369448/230321823-0a92b57b-71ea-48e1-a16f-fecf7e8616ef.png">

```
\int \frac{3 dz}{z}
```
<img width="107" alt="image" src="https://user-images.githubusercontent.com/19369448/230321894-6bfba8f2-1e0b-424a-a8ef-0d1e01514e07.png">

**Comment by tranleduy2000** [comment]
For `\angle` symbol,  example:  `3\angle2` should convert to `FromPolarCoordinates[{3, 2}]`
