### ISSUE TITLE
Perform check `arg1.isInteger()` not working for ApfloatNum with integer value.

### ISSUE THREAD

**Issue by tranleduy2000** [axkr/symja_android_library#727]
https://github.com/axkr/symja_android_library/blob/a5bb9d7c652a8942a6f56f3c2e68340118b53002/symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/builtin/LinearAlgebra.java#L2459

```java

    public void testHilbertMatrix() {
        IAST expr = F.HilbertMatrix(ApfloatNum.valueOf(new Apint("2")));
        ExprEvaluator exprEvaluator = new ExprEvaluator();
        IExpr result = exprEvaluator.eval(expr);
        assertEquals(result.toString(),
                "{{1,1/2},\n" +
                " {1/2,1/3}}");

    }
```

**Comment by axkr** [comment]
Please use `F.ZZ(...)` for creating Symja integers:
```java
    public void testHilbertMatrix() {
        IAST expr = F.HilbertMatrix(F.ZZ(2));
        ExprEvaluator exprEvaluator = new ExprEvaluator();
        IExpr result = exprEvaluator.eval(expr);
        assertEquals(result.toString(),
                "{{1,1/2},\n" +
                " {1/2,1/3}}");

    }
```

**Comment by tranleduy2000** [comment]
The problem is unable to calculate `HilbertMatrix(N(6, 30))`

**Comment by axkr** [comment]
> The problem is unable to calculate `HilbertMatrix(N(6, 30))`

Why not using `F.N( HilbertMatrix( F.ZZ(6) ), 30)` or why do you use `N(...))`?

**Comment by tranleduy2000** [comment]
I mean that the user enters directly `HilbertMatrix(N(6, 30))` to the console instead of using the Java code.
