### ISSUE TITLE
Ability to multiply associations outside of Cartesian product mode

### ISSUE THREAD

**Issue by AlfViklund** [axkr/symja_android_library#728]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

If necessary discuss the feature in the [Discord Symja chat][1].

[1]: https://discord.gg/tYknzr2qam

**Comment by AlfViklund** [comment]
I have written some junit tests to describe what I would like to achieve.
`    
@Test
    public void testTimes() {
        IExpr result = util.eval("Association[2025->10, 2026->11] * Association[2025->10, 2026->20]");
        IExpr expectedResult = util.eval("Association[2025->100, 2026->220]");
        Assert.assertEquals(expectedResult, result);
    }

    @Test
    public void testPlus() {
        IExpr result = util.eval("Association[2025->10, 2026->11] + Association[2025->10, 2026->20]");
        IExpr expectedResult = util.eval("Association[2025->20, 2026->31]");
        Assert.assertEquals(expectedResult, result);
    }

    @Test
    public void testSubtract() {
        IExpr result = util.eval("Association[2025->10, 2026->11] - Association[2025->10, 2026->20]");
        IExpr expectedResult = util.eval("Association[2025->0, 2026->-9]");
        Assert.assertEquals(expectedResult, result);
    }

    @Test
    public void testDivide() {
        IExpr result = util.eval("Association[2025->10, 2026->11] / Association[2025->10, 2026->20]");
        IExpr expectedResult = util.eval("Association[2025->1, 2026->(11/20)]");
        Assert.assertEquals(expectedResult, result);
    }
    `

**Comment by AlfViklund** [comment]
And I would also like to know if it is possible to add your own infix operators to the simja?

**Comment by axkr** [comment]
> And I would also like to know if it is possible to add your own infix operators to the symja?

At the moment I think you have to modify the core module to define your own infix operator.

If possible we want to use (a subset) of the operators in MMA:
- https://reference.wolfram.com/language/tutorial/OperatorInputForms.html

**Comment by AlfViklund** [comment]
Then how can I un-flag protected some functions so that I can override the logic of the arithmetic methods so that they work like in tests. I tried to do something like this
        util.eval("AssociationAdd(x_Association, y_Association) := AssociationThread[Keys[x] -> (Values[x] + Values[y])];");
    String redefinePlus = "Unprotect(Plus);" +
      "Plus(x_Association, y_Association) := AssociationAdd(x, y);" +
      "Plus(x_Association, y_?NumericQ) := x + AssociationThread[Keys[x] -> ConstantArray[y, Length[x]]];" +
      "Plus(y_?NumericQ, x_Association) := Plus(x, y);" +
      "Protect(Plus);";
