### ISSUE TITLE
Implement `plusReversed` for TexFormFactory (like `OutputFormFactory`)

### ISSUE THREAD

**Issue by tranleduy2000** [axkr/symja_android_library#753]
For input: `1+x-x^2`

I want to get the tex result in natural form:

`-x^2 - x + 1`

The current behavior is sorting the term in polynomial to an increasing degree.

**Comment by tranleduy2000** [comment]
Hi @axkr, the plus reverse option fails with the following test case:

```
  public void test001() {
    TeXFormFactory teXFormFactory = new TeXFormFactory(
      true, -1, -1, " \\cdot ");
    IExpr term = F.Plus(F.ZZ(-6), S.a);
    IASTAppendable ast = F.PlusAlloc(2);
    ast.append(term);
    ast.append(F.Style(F.ZZ(4), S.Red));
    StringBuilder buffer = new StringBuilder();
    teXFormFactory.convert(buffer, ast);
    assertEquals(buffer.toString(), "\\textcolor{red}{4} + a-6");
  }
```

```
Expected :\textcolor{red}{4}a-6
Actual   :\textcolor{red}{4} + a-6
```

**Comment by axkr** [comment]
the expresswion `F.Plus(F.ZZ(-6), S.a)` does an implicit sort on the arguments, because `Plus` has attribute `Orderless`.

To avoid this construct the expression with the `F#ast(final IExpr[] arr, final IExpr head)`
```java
  public void testPlusReversed002() {
    TeXFormFactory teXFormFactory = new TeXFormFactory(true, -1, -1, " \\cdot ");
    IExpr[] args = new IExpr[] {F.Style(F.ZZ(4), S.Red), F.ZZ(-6), S.a};
    IExpr term = F.ast(args, S.Plus);
    StringBuilder buffer = new StringBuilder();
    teXFormFactory.convert(buffer, term);
    assertEquals(buffer.toString(), //
        "a-6 + \\textcolor{red}{4}");
  }
```

**Comment by tranleduy2000** [comment]
> the expresswion `F.Plus(F.Style(F.ZZ(4), S.Red), F.ZZ(-6), S.a)` does an implicit sort on the arguments, because `Plus` has attribute `Orderless`.
> 
> To avoid this construct the expression with the `F#ast(final IExpr[] arr, final IExpr head)`
> 
> ```java
>   public void testPlusReversed002() {
>     TeXFormFactory teXFormFactory = new TeXFormFactory(true, -1, -1, " \\cdot ");
>     IExpr[] args = new IExpr[] {F.Style(F.ZZ(4), S.Red), F.ZZ(-6), S.a};
>     IExpr term = F.ast(args, S.Plus);
>     StringBuilder buffer = new StringBuilder();
>     teXFormFactory.convert(buffer, term);
>     assertEquals(buffer.toString(), //
>         "a-6 + \\textcolor{red}{4}");
>   }
> ```

There problem here there is a missing `+` character in output form: `\textcolor{red}{4}a-6` => \textcolor{red}{4}+a-6`
