### ISSUE TITLE
Swapped multiply and divide

### ISSUE THREAD

**Issue by js361014** [axkr/symja_android_library#787]
**Describe the bug**

For some reason IExpr::multiply and IExpr::divide sometimes behave as if "swapped". 

**To Reproduce**
Here are tests:
```
@Test
  public void test1() {
    Assertions.assertEquals("x*z^(1-y)", F.symjify("x").multiply(F.symjify("z").power(F.symjify("y").minus(F.ZZ(1)))).toString());
  }

  @Test
  public void test2() {
    Assertions.assertEquals("x/z^(1-y)", F.symjify("x").divide(F.symjify("z").power(F.symjify("y").minus(F.ZZ(1)))).toString());
  }
```

**Comment by axkr** [comment]
It's the output form which calls `Algebra.fractionalPartsTimesPower` where `z^(y-1)` is swapped to `z^(1-y)`. Because the first `-1`  assumes that the power "belongs" to the denominator:
- https://github.com/axkr/symja_android_library/blob/8ef5a72c4265d2c5aa75372ab92ebad76cb7d376/symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/form/output/OutputFormFactory.java#L635-L642

**Comment by js361014** [comment]
OK, I see. Can you examine why https://matheclipse.org/input?i=Solve({x==100,y==900,x/z^(1-y)==100},{x,y,z}) raises timeout exceeded? The solution here is z=1.

**Comment by axkr** [comment]
> The solution here is z=1.

no, there are much more solutions in the `Complexes` domain. 
The webserver is restricted with a timeout `Config.SERVER_REQUEST_TIMEOUT_SECONDS` of 30 seconds, but even in unrestricted mode the solutions isn't found after 30 minutes.

**Comment by js361014** [comment]
Is it possible to limit solutions domain to reals (including modifying some core methods)?

**Comment by axkr** [comment]
> Is it possible to limit solutions domain to reals (including modifying some core methods)?

Theoretical yes, you can add `Reals` or `Integers` as the last argument.
- https://github.com/axkr/symja_android_library/blob/master/symja_android_library/doc/functions/Solve.md 

but at the moment it works more like a "filter" which filters the `Reals` solution after the complete set of solutions was determined.
