### ISSUE TITLE
Rationalize[1.000007] returns 1 instead of a fraction

### ISSUE THREAD

**Issue by tranleduy2000** [axkr/symja_android_library#810]
```
Rationalize[1.000007,12]
Rationalize[1.000007]
```

Both inputs generate result `1` 

Expected result:
```
1000007/1000000
```

<img width="493" alt="image" src="https://github.com/axkr/symja_android_library/assets/19369448/7fe0f823-9700-4a84-9da3-5f228513339f">

**Comment by axkr** [comment]
Same as in MMA:
![image](https://github.com/axkr/symja_android_library/assets/3109793/ee0a063c-5ff9-46a9-a6db-f7c69da94612)

This will work as expected:

```
Rationalize[1.00007]
```

Do you need a rationalize function for `Apfloat` numbers?
Maybe opening an issue in apfloat for this may help?
- https://github.com/mtommila/apfloat

**Comment by tranleduy2000** [comment]
Is there a way to convert `1.00007` into fraction?
I would like to ask a general way to do that, not a specific implementation for a `INumber`

**Comment by axkr** [comment]
After the first parser step we have a parsed `NumStr`
- https://github.com/axkr/symja_android_library/blob/master/symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/NumStr.java

where the `fFloatStr` can be parsed and transformed to a "decimal rationalized" form. 
After the evaluation (especially as an argument to `Rationalize`) we often only have a `Num` object which only contains a binary `double value`.

**Comment by tranleduy2000** [comment]
Understood.
So I must preprocess the input before passing it to Symja to get the symbolic form of a decimal value.
