### ISSUE TITLE
Missing atan2 rules

### ISSUE THREAD

**Issue by tranleduy2000** [axkr/symja_android_library#84]
In new version, library can not calculate `ArcTan(-9*Sqrt(2),0)`

![image](https://user-images.githubusercontent.com/19369448/46285753-c9760c80-c5a6-11e8-8b75-26f0700a8724.png)

![image](https://user-images.githubusercontent.com/19369448/46285772-dc88dc80-c5a6-11e8-9747-d7f6c20542ae.png)

**Comment by tranleduy2000** [comment]
New bug, calculate `ArcTan(Re(9*Cos(5)+I*9*Sin(5)),Im(9*Cos(5)+I*9*Sin(5)))` give exception.

![image](https://user-images.githubusercontent.com/19369448/46336647-9b9bd100-c655-11e8-95e7-6554e4945919.png)

![image](https://user-images.githubusercontent.com/19369448/46336670-ace4dd80-c655-11e8-8b4a-7715a0bf6ed8.png)

**Comment by tranleduy2000** [comment]
`ArcTan(0, Pi)` should return `Pi/2` instead of `ComplexInfinity`

**Comment by axkr** [comment]
The commit should solve the problem
