### ISSUE TITLE
[BUG] Integrate[ x * ArcSin[x], {x, 0, 1}] returns wrong result (Pi/4 instead of  Pi/8)

### ISSUE THREAD

**Issue by tranleduy2000** [axkr/symja_android_library#851]
Here is the input:
```
Integrate[ x * ArcSin[x], {x, 0, 1}]
```

<img width="342" alt="image" src="https://github.com/axkr/symja_android_library/assets/19369448/79a94905-8814-4854-b8f9-4d2dbc452a5c">

Result from Wolfram|Alpha

<img width="867" alt="image" src="https://github.com/axkr/symja_android_library/assets/19369448/6f123f48-1129-41c9-baaf-fcc42f6bc71d">

**Comment by axkr** [comment]
Please reopen if necessary
