### ISSUE TITLE
Implement `AbstractAssumptions#assumeInteger` for integer values

### ISSUE THREAD

**Issue by tranleduy2000** [axkr/symja_android_library#854]
The current implementation of `Element` functions does not work with numeric data types (`ApfloatNum`, `ApcomplexNum`, `Num`, ...)

Example:
```
aa = 1;
Element(aa, Integers)
>> Element(aa, Integers)
```
<img width="444" alt="image" src="https://github.com/axkr/symja_android_library/assets/19369448/f56b91a4-4151-45d7-8d43-355c807e962f">

Expected result: 
It should return `True` as same as `IInteger`
<img width="440" alt="image" src="https://github.com/axkr/symja_android_library/assets/19369448/75ee3045-4dbe-4372-9f86-b7d25b2e5471">

**Comment by axkr** [comment]
That's the same behaviour as in Mathematica. Because `N` converts to a a floating point number it's not assumed to be part of `Integers`.

**Comment by tranleduy2000** [comment]
Could you please add an option (like `Config#ACCEPT_NUMERIC_INTEGER_IN_INTEGERS_DOMAIN`) for this purpose?

**Comment by axkr** [comment]
Please reopen if necessary
