### ISSUE TITLE
Improve `FullSimplify` for input `1/(sqrt[7] - 2 sqrt[2]) + 1/(sqrt[7] + 2 sqrt[2])`

### ISSUE THREAD

**Issue by tranleduy2000** [axkr/symja_android_library#856]
There is the input:
```mma
1/(sqrt[7] - 2 sqrt[2]) + 1/(sqrt[7] + 2 sqrt[2]) // FullSimplify
```

By reducing to the common denominator, the input can be simplified to: 
```mma
-2 * Sqrt[7]
```

![image](https://github.com/axkr/symja_android_library/assets/19369448/ac57b714-3531-4127-a0db-f393fef300db)

**Comment by axkr** [comment]
The `Together`function should handle this:

**Comment by tranleduy2000** [comment]
```
(2 *Sqrt[6] - Sqrt[3]) / (Sqrt[2] - 4) // FullSimplify
```

<img width="976" alt="image" src="https://github.com/axkr/symja_android_library/assets/19369448/cb8d978c-b60d-4888-92c2-45e17a802dde">

By multiplying both numerator and denominator with denominator's conjugate, the result can be simplified to `-Sqrt[3/2]`

```mathematica
(2 *Sqrt[6] - Sqrt[3]) / (Sqrt[2] - 4) 
= (2 *Sqrt[6] - Sqrt[3]) * (Sqrt[2] + 4)  / (2 - 16)
= 7 * Sqrt[6] / -14
=  -Sqrt[3 / 2]
```

**Comment by tranleduy2000** [comment]
Another case:
```mathematica
(4+3*Sqrt[2]+Sqrt[3]+Sqrt[6])/(2+Sqrt[2]+Sqrt[3]) // FullSimplify
```

Expected result:
```
1+Sqrt[2]
```

<img width="954" alt="image" src="https://github.com/axkr/symja_android_library/assets/19369448/a5d35f18-9d20-4d61-bd18-03a691ae3a4c">

**Comment by axkr** [comment]
I think the `Apart` function needs to be smarter to evaluate to `1+Sqrt(2)`
