### ISSUE TITLE
Surd(I, 3) not working

### ISSUE THREAD

**Issue by tranleduy2000** [axkr/symja_android_library#87]
![image](https://user-images.githubusercontent.com/19369448/46472596-ed845880-c807-11e8-8cfc-68fa42fb2c61.png)

![image](https://user-images.githubusercontent.com/19369448/46472582-e2c9c380-c807-11e8-8cde-e75d38dac966.png)

**Comment by axkr** [comment]
`Surd[I,3]` returns unevaluated in the wolfram language. See [Surd](https://reference.wolfram.com/language/ref/Surd.html)
