### ISSUE TITLE
Pattern-matching with {OneIdentity, Orderless} different from Mathematica

### ISSUE THREAD

**Issue by rebcabin** [axkr/symja_android_library#89]
# Submit a feature request or bug report

Replace any "X" with your information.

---

### Is this a request for a feature or a bug report?

bug report

### What is the current behavior?

When presented with the substitution rule `(eqv[p,q,r] /. {eqv[x_,y_] :> {x,y}})` for all combinations of attributes `Flat`, `OneIdentity`, and `Orderless`, SymJa produces one result different from Mathematica's, namely the result for `{OneIdentity, Orderless}`. This difference could have profound, subtle, rippling effects throughout the system because the entire system rests on the pattern matcher.

Here is what SymJa produces:

```
{{{Flat},                       p,      {eqv[q,r]}},
 {{OneIdentity},                eqv[p], {eqv[q,r]}},
 {{Orderless},                  p,      eqv[q,r]},
 {{Flat,OneIdentity},           p,      eqv[q,r]},
 {{Flat,Orderless},             p,      {eqv[q,r]}},
 {{OneIdentity,Orderless},      eqv[p], {eqv[q,r]}},  <~~~ DIFF'T FROM MATHEMATICA
 {{Flat,OneIdentity,Orderless}, p,      eqv[q,r]}}

```
### If this is a bug report, please provide steps to reproduce:

    mvn exec:java@mma -pl matheclipse-core

    Table[Module[{ e = (eqv[p,q,r] /. {eqv[x_,y_] :> {x,y}}) }, ClearAll[eqv]; SetAttributes[eqv,j]; {j, First@e, Rest@e}], {j, Flatten[Table[Union[Sort/@Permutations[{Flat,Orderless,OneIdentity}, {i}]], {i,3}], 1]}]

### What is the expected or desired behavior?  

Mathematica's results for `{OneIdentity, Orderless}` are *different* from SymJa's. Here is what Mathematica produces.

       {{{Flat},                        p, {eqv[q, r]}},
       {{OneIdentity},                  eqv[p], {eqv[q, r]}},
       {{Orderless},                    p, eqv[q, r]},
       {{Flat, OneIdentity},            p, eqv[q, r]},
       {{Flat, Orderless},              p, {eqv[q, r]}},
       {{OneIdentity, Orderless},       q, {eqv[p, r]}},  <~~~ DIFF'T FROM SYMJA
       {{Flat, OneIdentity, Orderless}, p, eqv[q, r]}}

### Please provide use cases for changing the current behavior:

Same as the repro steps above

### Please describe your development environment (OS, browser, etc.):

Linux Ubuntu 18.04 openJDK 10.0.2
Mathematica 11.03

### Other relevant information:

See this related bug in Mathics. https://github.com/mathics/Mathics/issues/747 I think SymJa does a better job because `Flat` is a more important attribute than either `Orderless` or `OneIdentity`. Still, all these programs should perfectly repro Mathematica IMO.

**Comment by axkr** [comment]
Could you reduce this to a simpler JUnit test?

Something like:
```
	public void testOneIdentityOrderless() {
		// github issue 89
		check("SetAttributes(f, {Orderless, OneIdentity})", "");
		check("f(p, q) /. {f(x_,y_) :> {x,y}}", "{p,q}");
		check("", "");
	}
```

**Comment by rebcabin** [comment]
I discovered that it matters whether the attributes are specified before the pattern is parsed, or after. The following specifies the attributes first; my example above specifies the pattern first. The results are different Mathematica-Mathematica, Mathematica-SymJa, and SymJa-SymJa

    allAtts = Flatten[Table[Union[Sort /@ Permutations[
                {Flat, Orderless, OneIdentity}, {i}]], {i, 3}], 1]    
    Table[Module[{e},  
        ClearAll[eqv];  SetAttributes[eqv, j];  
        e = (eqv[p, q, r] /. {eqv[x_, y_] :> {x, y}});  {j, First@e, Rest@e}  ], 
        {j, allAtts}]

Mathematica

        {{{Flat},                         eqv[p], {eqv[q, r]}}, 
         {{OneIdentity},                  p,       eqv[q, r]}, 
         {{Orderless},                    p,       eqv[q, r]}, 
         {{Flat, OneIdentity},            p,      {eqv[q, r]}}, 
         {{Flat, Orderless},              q,      {eqv[p, r]}}, 
         {{OneIdentity, Orderless},       p,       eqv[q, r]}, 
         {{Flat, OneIdentity, Orderless}, p,      {eqv[q, r]}}}

SymJa
          
        {{{Flat},                         eqv[p], {eqv[q,r]}},
         {{OneIdentity},                  p,       eqv[q,r]},
         {{Orderless},                    p,       eqv[q,r]},
         {{Flat, OneIdentity},            p,      {eqv[q,r]}},
         {{Flat, Orderless},              eqv[p], {eqv[q,r]}},
         {{OneIdentity, Orderless},       p,       eqv[q,r]},
         {{Flat, OneIdentity, Orderless}, p,      {eqv[q,r]}}}

**Comment by rebcabin** [comment]
> Could you reduce this to a simpler JUnit test?

I'm still investigating (there are several posts in StackExchange that I will quote here in a few minutes; apparently there were some breaking changes in Mathematica 10.1). When I get a better understanding, I'll work up some tests.

**Comment by rebcabin** [comment]
Investigating: Relevant posts in StackExchange, purport to explain the correct, desired, expected behavior in multiple versions of Mathematica. "Correct," "desired," and "expected" may not be all the same and may not be consistent across versions of Mathematica.

https://mathematica.stackexchange.com/questions/71463/orderless-pattern-matching
https://mathematica.stackexchange.com/questions/124372/about-oneidentity
https://mathematica.stackexchange.com/questions/121564/what-has-changed-in-pattern-matching-functions-with-the-orderless-attribute
https://mathematica.stackexchange.com/questions/94432/pattern-does-not-match-with-orderless-head

**Comment by axkr** [comment]
Yes go ahead. I will look at it next weel

**Comment by rebcabin** [comment]
# EXHAUSTIVE 3-2 SUBSTITUTION TEST

Adding tests for substitution of `{x, y}` for pattern `eqv[x_, y_]` in `eqv[p,q,r]` under all combinations of attributes `Flat`, `OneIdentity`, and `Orderless` on the head symbol `eqv`. Note that pattern `eqv[x_, y_]` does not match `eqv[p, q, r]` when `eqv` has no attributes.

## TWO VARIATIONS

It matters whether attributes are set before or after the substitutions are defined. Here is a list of all seven combinations of attributes:

    allAtts =
      Flatten[Table[
        Union[Sort /@
          Permutations[{Flat, Orderless, OneIdentity}, {i}]], {i, 3}], 1]

## ATTRIBUTES AFTER SUBSTITUTION DEFINED

Here is Mathematica's ground truth when attributes are set AFTER the substitution is defined:

    Table[Module[{e = (eqv[p, q, r] /. {eqv[x_, y_] :> {x, y}})},
       ClearAll[eqv]; SetAttributes[eqv, j];
       {j, First@e, Rest@e}],
     {j, allAtts}]

### Mathematica 11.3.0.0

    {{{Flat},                         p, eqv[q, r]},    <--- Symja differs at console
     {{OneIdentity},                  eqv[p], {eqv[q, r]}},
     {{Orderless},                    p, eqv[q, r]},
     {{Flat, OneIdentity},            p, eqv[q, r]},
     {{Flat, Orderless},              p, {eqv[q, r]}},
     {{OneIdentity, Orderless},       q, {eqv[p, r]}},  <--- SymJa differs
     {{Flat, OneIdentity, Orderless}, p, eqv[q, r]}}

### SymJa

**SUB_ISSUE 89.1: An extra list level is in the console output for `Flat`**

SymJa produces different results at the console than in the unit-test framework.

Consider the unit test `testOneIdentityOrderless` in `LowercaseTestCase.java`. When the input text of the unit test is copy-pasted to the console in Mathematica mode, we get

    $ mvn exec:java@mma -pl matheclipse-core
    ▶    Table[Module[{ e = (eqv[p,q,r] /. {eqv[x_,y_] :> {x,y}}) }, ClearAll[eqv]; SetAttributes[eqv,j]; {j, First@e, Rest@e}], {j, Flatten[Table[Union[Sort/@Permutations[{Flat,Orderless,OneIdentity}, {i}]], {i,3}], 1]}]
    In [1]: Table[Module[{ e = (eqv[p,q,r] /. {eqv[x_,y_] :> {x,y}}) }, ClearAll[eqv]; SetAttributes[eqv,j]; {j, First@e, Rest@e}], {j, Flatten[Table[Union[Sort/@Permutations[{Flat,Orderless,OneIdentity}, {i}]], {i,3}], 1]}]
    Out[1]: {{{Flat},p,{eqv[q,r]}},{{OneIdentity},eqv[p],{eqv[q,r]}},{{Orderless},p,eqv[q,r]},{{Flat,OneIdentity},p,eqv[q,r]},{{Flat,Orderless},p,{eqv[q,r]}},{{OneIdentity,Orderless},eqv[p],{eqv[q,r]}},{{Flat,OneIdentity,Orderless},p,eqv[q,r]}}

At console, prettified:

    {{{Flat},                        p, {eqv[q, r]}},
    {{OneIdentity},                  eqv[p], {eqv[q, r]}},
    {{Orderless},                    p, eqv[q, r]},
    {{Flat, OneIdentity},            p, eqv[q, r]},
    {{Flat, Orderless},              p, {eqv[q, r]}},
    {{OneIdentity, Orderless},       eqv[p], {eqv[q, r]}},
    {{Flat, OneIdentity, Orderless}, p, eqv[q, r]}}


Notice that the result for `Flat` has the second term, `{eqv[q,r]}` in a list. However, the expected output term --- the second argument --- in the text of the unit test reads:

    {{{Flat},p,eqv(q,r)},{{OneIdentity},eqv(p),{eqv(q,r)}},{{Orderless},p,eqv(q,r)},{{Flat,OneIdentity},p,eqv(q,r)},{{Flat,Orderless},p,{eqv(q,r)}},{{OneIdentity,Orderless},eqv(p),{eqv(q,r)}},{{Flat,OneIdentity,Orderless},p,eqv(q,r)}}

In unit test, prettified:

    {{{Flat},                        p, eqv(q, r)},
    {{OneIdentity},                  eqv(p), {eqv(q, r)}},
    {{Orderless},                    p, eqv(q, r)},
    {{Flat, OneIdentity},            p, eqv(q, r)},
    {{Flat, Orderless},              p, {eqv(q, r)}},
    {{OneIdentity, Orderless},       eqv(p), {eqv(q, r)}},
    {{Flat, OneIdentity, Orderless}, p, eqv(q, r)}}

Notice that the result for `Flat` DOES NOT have the second term, `eqv(q,r)`, in a list.

That result is consistent with Mathematica, so we conclude that the text of the unit test is correct and that there is something wrong with the console.

**SUB_ISSUE 89.2: Result for `OneIdentity, Orderless` differs from Mathematica**

We argue the result for unit test `testOneIdentityOrderless` in `LowercaseTestCase.java` result for `{OneIdentity, Orderless}` SHOULD NOT PASS because Mathematica's (ground truth) would require the following:

    {{OneIdentity, Orderless}, q, {eqv[p, r]}},       <--- MMA says
    {{OneIdentity, Orderless}, eqv[p], {eqv[q, r]}},  <--- SymJa says


## ATTRIBUTES BEFORE SUBSTITUTION DEFINED

In this case, SymJa produces the same result at the console as in the unit test, but still differs from ground truth (Mathematica 11.3.0.0).

Here is Mathematica's ground truth when attributes are set BEFORE substitutions are defined.

    Table[Module[{e},
        ClearAll[eqv]; SetAttributes[eqv, j];
        e = (eqv[p, q, r] /. {eqv[x_, y_] :> {x, y}})
      {j, First@e, Rest@e}  ], {j, allAtts}]

### Mathematica 11.3.0.0

    {{{Flat},                         eqv[p], {eqv[q, r]}},
     {{OneIdentity},                  p,       eqv[q, r]},
     {{Orderless},                    p,       eqv[q, r]},
     {{Flat, OneIdentity},            p,      {eqv[q, r]}},
     {{Flat, Orderless},              q,      {eqv[p, r]}},  <--- SymJa differs
     {{OneIdentity, Orderless},       p,       eqv[q, r]},
     {{Flat, OneIdentity, Orderless}, p,      {eqv[q, r]}}}

### SymJa

    {{{Flat},                         eqv[p], {eqv[q,r]}},
     {{OneIdentity},                  p,       eqv[q,r]},
     {{Orderless},                    p,       eqv[q,r]},
     {{Flat, OneIdentity},            p,      {eqv[q,r]}},
     {{Flat, Orderless},              eqv[p], {eqv[q,r]}},  <--- MMA differs
     {{OneIdentity, Orderless},       p,       eqv[q,r]},
     {{Flat, OneIdentity, Orderless}, p,      {eqv[q,r]}}}

**SUB_ISSUE 89.3: ATTRIBUTES-BEFORE result for `Flat, Orderless` differs from Mathematica**

## CONCLUSION

An attempt to unroll these tests produce puzzling results. I am opening a question in mathematica.stackexchange.com, and there will be some follow up here. However, despite these new puzzles, this issue has shown differences between SymJa and Mathematica. Recall that bugs in pattern-matching were introduced in or before Mathematica 10.1 and fixed at latest in 11.3.0.0, so ground truth must be tested in appropriate versions of Mathematica.

**Comment by rebcabin** [comment]
Here is my open question on stackexchange. I hope that answers will add some clarity to this issue, which I regret has become much more complicated than I thought it would:

https://mathematica.stackexchange.com/questions/183319/big-and-little-surprises-when-unrolling-tests-of-pattern-matching-and-attributes

**Comment by rebcabin** [comment]
It's a puzzle, because sfaik, `Orderless` should imply that `fo[p, q, r, s, t]` equals `fo[p, r, q, s, t]` and, in fact, all other 118 permutations of the arguments. Internally, I have always assumed that MMA simply `Sort`s the argument list of `Orderless` symbols, but that would predict that we should get `{p, q, fo[r, s, t]}` as the final result. `Flat` implies that `fo[p, q, r, s, t]` equals `fo[p, q, fo[r, s, t]]` (amidst all other permutations of the arguments), so the `Flat` part of the answer is easy to understand.

I'm hoping that a Wolfram insider will reply to my post on stackexchange, which has several other `p q r` `p r q` inversions under other circumstances.

**Comment by rebcabin** [comment]
Ok, someone from Wolfram answered. I was confused (I already knew that), and my code was not doing what I thought it was doing. I now see clearly. In my next PR, I will clarify the unit tests and make a new statement.

**Comment by rebcabin** [comment]
These are the tests that make sense after reviewing the answers to my questions on stackexchange. I tried to merge upstream/master, but I am getting two new, unrelated test failures after the trial merge. I will amend the pull request with the failing tests in the commit comment.

```
      check("Module[{e}, ClearAll[eqv]; SetAttributes[eqv, {Flat}]; eqv[p, q, r] /. {eqv[x_, y_] :> {x, y}}]",
            "{eqv(p),eqv(q,r)}");

      check("Module[{e}, ClearAll[eqv]; SetAttributes[eqv, {Flat, OneIdentity}]; eqv[p, q, r] /. {eqv[x_, y_] :> {x, y}}]",
            "{p,eqv(q,r)}");

      // This test currently fails with {eqv(p),eqv(q,r)} as the actual. The expected below is the result from
		// Mathematica 11.3.0.0. TODO: Make this test pass.
      // check("Module[{e}, ClearAll[eqv]; SetAttributes[eqv, {Flat, Orderless}]; eqv[p, q, r] /. {eqv[x_, y_] :> {x, y}}]",
      //      "{q,eqv(p,r)}");

      check("Module[{e}, ClearAll[eqv]; SetAttributes[eqv, {Flat, OneIdentity, Orderless}]; eqv[p, q, r] /. {eqv[x_, y_] :> {x, y}}]",
            "{p,eqv(q,r)}");

```

**Comment by rebcabin** [comment]
Actually, after all this work, I THINK SYMJA IS CORRECT and Mathematica is wrong. I am going to revise my PR to make the test expect `{eqv(p), eqv(q, r)}`, which I believe to be correct for `{Flat, Orderless}`. I will close the issue after that PR is accepted, and continue the debate on stackexchange.
