### ISSUE TITLE
`Mod(N(5652, 30)^42*23^77,5929)` return 0 instead of 4624

### ISSUE THREAD

**Issue by tranleduy2000** [axkr/symja_android_library#976]
The `Mod` function returns wrong result with the following input:

```
Mod(N(5652, 30)^42*23^77,5929) 
```

<img width="431" alt="image" src="https://github.com/axkr/symja_android_library/assets/19369448/a84d66dd-62e7-4fd2-8ce0-3f46b9cb94a9">

Expected result:

```
4624
```

<img width="350" alt="image" src="https://github.com/axkr/symja_android_library/assets/19369448/9367bbbe-9c07-4906-b69f-3799d6071397">

**Comment by axkr** [comment]
The precision for the internal `apfloat` data type calculation must be increased.
For example to 300:

```mma
>> Mod(N(5652, 300)^42*23^77,5929)
4623.999999999999999999999999999999999999999999461282372
```

**Comment by tranleduy2000** [comment]
Thanks for the trick!
